window.CODEX_DIARY_UI_COPY = {
  en: {
    "app.title": "Codex Diary",
    "brand.sub": "Turn Chronicle summaries into a diary",
    "nav.diary": "Diary",
    "nav.calendar": "Calendar",
    "nav.archive": "Archive",
    "side.recent": "Recent dates",
    "side.weekly": "Weekly collections",
    "quote.html": "Daily notes<br />shape tomorrow <span class=\"heart\">♡</span>",
    "settings.title": "Settings",
    "date.label": "Base date",
    "date.missing": "Choose a date",
    "action.prevDay": "Previous day",
    "action.nextDay": "Next day",
    "action.pickDate": "Choose date",
    "action.today": "Today",
    "action.more": "More",
    "action.change": "Change",
    "action.close": "Close",
    "view.diary": "Diary",
    "view.report": "Report",
    "view.raw": "Markdown",
    "menu.viewWeek": "View this week",
    "menu.copy": "Copy current view",
    "menu.external": "Open in external app",
    "settings.panelAria": "Settings panel",
    "settings.eyebrow": "Preferences",
    "settings.summaryAria": "Settings summary",
    "settings.summaryStrong": "Tune the diary flow to your rhythm.",
    "settings.summaryCopy":
      "Set the language, day boundary, and save behavior once to keep a steady routine.",
    "settings.introBadge": "Default language: {{language}}",
    "settings.outputSection": "Language & Output",
    "settings.languageLabel": "Language",
    "settings.languageHint": "Both the diary output and the app UI follow this language.",
    "settings.lengthLabel": "Diary length",
    "settings.lengthHint": "Choose how short or full the generated diary should feel.",
    "settings.boundaryLabel": "Day boundary",
    "settings.boundaryHint": "Records before this time are grouped into the previous day.",
    "settings.modeLabel": "Generation mode",
    "settings.modeFinalize": "Finalize diary",
    "settings.modeDraft": "Update draft",
    "settings.autoSaveTitle": "Save automatically after generation",
    "settings.autoSaveHint": "Save the result to the output folder right away.",
    "settings.pathsSection": "Paths",
    "settings.sourceLabel": "Source folder",
    "settings.outputLabel": "Output folder",
    "generate.finalize": "Create diary",
    "generate.draft": "Update draft",
    "generate.todayFinalize": "Create today's entry",
    "generate.todayDraft": "Update today's draft",
    "generate.connect": "Create after connecting Codex",
    "generate.connectTitle": "Connect Codex before generating.",
    "generate.cancel": "Cancel",
    "generate.cancelling": "Cancelling...",
    "generate.cancelTitle": "Cancel the current generation.",
    "generate.busy": "Generating...",
    "loading.badge": "Creating in {{language}}",
    "loading.titleWithDate": "Quietly weaving {{date}} into a diary",
    "loading.titleToday": "Quietly weaving today into a diary",
    "loading.copy":
      "Give it a moment. Your Chronicle notes are being shaped into a diary and report, then the result will open right here.",
    "loading.step.collect": "Reading Chronicle summaries",
    "loading.step.organize": "Sorting the day's flow",
    "loading.step.write": "Asking Codex for the draft",
    "loading.step.finish": "Polishing the in-app result",
    "loading.detail.collect": "Collecting the day's Markdown summaries first.",
    "loading.detail.organize": "Removing overlap and lining events up by time.",
    "loading.detail.write": "Preparing the factual diary draft through Codex.",
    "loading.detail.writePrepare": "Packing today's context for Codex.",
    "loading.detail.writeStart": "Starting the Codex draft run.",
    "loading.detail.writeWait": "Waiting for Codex to finish the draft.",
    "loading.detail.writeCheck": "Checking the generated Markdown result.",
    "loading.detail.writeReady": "Handing the draft back to the app.",
    "loading.detail.cancel": "Stopping the current draft run.",
    "loading.detail.cancelled": "The generation was cancelled.",
    "loading.detail.finish": "Formatting the result so it opens right here.",
    "loading.elapsed": "{{seconds}}s elapsed",
    "loading.meta": "It will appear here automatically.",
    "loading.meta.slow":
      "Longer days or Very long entries can take around 4 to 5 minutes. We'll let you know when it's ready.",
    "path.default": "Use default folder",
    "boundary.label": "{{hour}}:00",
    "boundary.chip": "{{hour}}:00 boundary",
    "empty.report": "No report is available yet.",
    "empty.diary": "There is no diary to display yet.",
    "empty.titleWithDate": "Create an entry for {{date}}?",
    "empty.titleToday": "Want to quietly capture today?",
    "empty.copyWithDate":
      "No saved diary exists for this date yet. Use the create button to generate it immediately in {{language}}.",
    "empty.copyToday":
      "Use the create button and Chronicle summaries will be shaped into both a report and a diary.",
    "diary.title": "Today's diary",
    "mood.label": "Today's mood",
    "summary.label": "One-line summary",
    "memo.placeholder": "Write a short note you want to keep from today.",
    "memo.save": "Save",
    "memo.saved": "Saved your memo.",
    "foot.saved": "Auto-saved",
    "foot.preview": "Preview",
    "foot.modeFinalize": "Final diary",
    "foot.modeDraft": "Draft update",
    "foot.writtenAt": "Written at",
    "report.today": "What I did today",
    "report.highlights": "Highlights",
    "report.blockers": "Blockers",
    "report.tomorrow": "Tomorrow",
    "report.reflection": "Short reflection",
    "carryover.title": "Carried into today",
    "carryover.subtitle": "{{count}} task(s) waiting here",
    "carryover.from": "From {{date}}",
    "todo.carryForward": "Add to tomorrow",
    "todo.carriedForward": "Already added to tomorrow",
    "todo.markDone": "Mark done",
    "todo.markOpen": "Mark open",
    "timeline.title": "Timeline flow",
    "timeline.more": "Show {{count}} more",
    "timeline.all": "Expand all ({{count}})",
    "timeline.collapse": "Collapse all",
    "timeline.status": "Showing {{visible}} now · {{remaining}} more left",
    "calendar.savedCount": "{{count}} saved",
    "calendar.weekSection": "Weekly collections",
    "calendar.weekRecords": "{{count}} entries",
    "archive.eyebrow": "Archive",
    "archive.title": "Browse daily notes and weekly bundles in one place",
    "archive.copy": "Keep the sidebar light and use the main area to browse saved diaries.",
    "archive.recentSection": "Recent dates · {{count}}",
    "archive.weeklySection": "Weekly bundles · {{count}}",
    "archive.emptyDaily": "No saved diaries yet.",
    "archive.emptyWeekly": "No weekly bundles yet.",
    "side.emptyDaily": "No saved diaries yet",
    "side.emptyWeekly": "No weekly bundles yet",
    "saved.diary": "Saved diary",
    "saved.records": "{{count}} entries",
    "status.text.connected": "Codex Ready",
    "status.text.connect": "Connect Codex",
    "status.text.check": "Check Codex",
    "status.text.loading": "Checking Codex",
    "status.action.connect": "Connect",
    "status.action.check": "Check",
    "status.modelLabel": "Codex model",
    "status.detail.connected": "Ready to create a diary.",
    "status.detail.login": "Login is required.",
    "status.detail.wait": "Please wait a moment.",
    "connect.badge": "Codex",
    "connect.title": "Connect Codex first",
    "connect.body.connected":
      "Codex is ready, so you can pick a date and generate an entry right away.",
    "connect.body.default": "Check your Codex login status first.",
    "readiness.title": "Before creating",
    "readiness.prereqTitle": "Chronicle summaries are required",
    "readiness.prereqBody":
      "Codex Diary does not read recordings or screenshots directly. Turn on Chronicle first, then use the folder where Chronicle writes Markdown summaries.",
    "readiness.sourceCount": "{{count}} Markdown files",
    "readiness.sourceMissing": "No Chronicle summary folder found",
    "readiness.sourceEmpty": "No Chronicle Markdown summaries found",
    "readiness.outputReady": "Ready",
    "readiness.outputMissing": "Created automatically when saving",
    "footer.ready":
      "Pick a date and generate a record to read the diary and report right here in the app.",
    "footer.connectFirst": "Connect Codex first.",
    "footer.generating":
      "Reading Chronicle summaries and creating the selected day's entry in {{language}}...",
    "footer.cancelling": "Cancelling the current generation...",
    "footer.cancelled": "Cancelled the generation.",
    "footer.generateFailed": "Generation failed.",
    "footer.connected":
      "Pick a date and generate a record to read the diary and report right here in the app.",
    "footer.rechecked": "Checked the Codex connection status again.",
    "footer.connectFailed": "Failed to connect Codex.",
    "footer.noSavedForDate":
      "No saved diary exists for {{date}}. Generating again will overwrite that day's record.",
    "footer.noSavedForDateCalendar":
      "No saved diary exists for {{date}}. Generate it and it will be saved in {{language}}.",
    "footer.openDiaryFailed": "Couldn't open the diary for {{date}}.",
    "footer.openedDiary": "Opened the diary for {{date}}.",
    "footer.openWeekFailed": "Couldn't open the weekly view.",
    "footer.openedWeek": "Opened the weekly view for {{label}}.",
    "footer.calendarHint": "Pick a date in the calendar tab and continue from there.",
    "footer.generated":
      "Opened the diary for {{date}} in {{language}}.{{saved}}",
    "toast.codexReady": "Codex is ready",
    "toast.sourceChanged": "Source folder updated",
    "toast.outputChanged": "Output folder updated",
    "toast.nothingToCopy": "Nothing to copy",
    "toast.copied": "Copied",
    "toast.copyFailed": "Copy failed",
    "toast.noSavedFile": "There is no saved file.",
    "toast.openExternalFailed": "Could not open the saved file.",
    "toast.cancelled": "Cancelled",
    "toast.todayAdjusted": "Jumped to today's effective date",
    "toast.languageChanged": "Language changed to {{language}}",
    "toast.lengthChanged": "Diary length changed to {{length}}",
    "toast.modelChanged": "Codex model changed to {{model}}",
    "toast.todoCarried": "Added to {{date}}.",
    "toast.todoAlreadyCarried": "Already added to {{date}}.",
    "toast.todoUpdated": "Updated the task.",
    "warning.webview": "The WebView bridge is not ready.",
    "warning.timeout":
      "The response is taking longer than {{seconds}} seconds. Longer days can take 4 to 5 minutes, but this run may need to be tried again.",
    "length.short": "Short",
    "length.medium": "Medium",
    "length.long": "Long",
    "length.very-long": "Very long",
    "tag.today": "today",
    "tag.decisions": "decisions",
    "tag.blockers": "blockers",
    "tag.tomorrow": "tomorrow",
    "tag.diary": "diary",
    "mood.sparkle": "Sparkly",
    "mood.happy": "Happy",
    "mood.soft": "Calm",
    "mood.tired": "Tired",
    "mood.blue": "Blue",
  },
  ko: {
    "app.title": "Codex Diary",
    "brand.sub": "Chronicle 요약을 일기로",
    "nav.diary": "일기",
    "nav.calendar": "캘린더",
    "nav.archive": "보관함",
    "side.recent": "최근 날짜",
    "side.weekly": "주간 모아보기",
    "quote.html": "매일의 기록이<br />내일의 나를 만든다 <span class=\"heart\">♡</span>",
    "settings.title": "설정",
    "date.label": "기준 날짜",
    "date.missing": "날짜를 골라 주세요",
    "action.prevDay": "전날",
    "action.nextDay": "다음날",
    "action.pickDate": "날짜 선택",
    "action.today": "오늘로",
    "action.more": "더 보기",
    "action.change": "변경",
    "action.close": "닫기",
    "view.diary": "일기",
    "view.report": "보고서",
    "view.raw": "Markdown",
    "menu.viewWeek": "해당 주 보기",
    "menu.copy": "현재 보기 복사",
    "menu.external": "외부 앱으로 열기",
    "settings.panelAria": "설정 패널",
    "settings.eyebrow": "환경 설정",
    "settings.summaryAria": "설정 요약",
    "settings.summaryStrong": "기록 흐름을 차분하게 맞춰 둘 수 있어요.",
    "settings.summaryCopy":
      "출력 언어, 하루 경계 시각, 저장 방식을 먼저 정해 두면 매일 같은 리듬으로 일기를 만들 수 있어요.",
    "settings.introBadge": "기본 언어: {{language}}",
    "settings.outputSection": "출력",
    "settings.languageLabel": "언어",
    "settings.languageHint": "생성 결과와 앱 UI가 이 언어를 함께 따라가요.",
    "settings.lengthLabel": "일기 길이",
    "settings.lengthHint": "생성되는 일기 분량을 짧게부터 매우 길게까지 고를 수 있어요.",
    "settings.boundaryLabel": "하루 경계 시각",
    "settings.boundaryHint": "이 시각 이전 기록은 전날 일기에 포함돼요.",
    "settings.modeLabel": "생성 모드",
    "settings.modeFinalize": "최종 일기",
    "settings.modeDraft": "초안 갱신",
    "settings.autoSaveTitle": "생성 후 자동으로 저장하기",
    "settings.autoSaveHint": "생성 직후 결과를 출력 폴더에 바로 저장해요.",
    "settings.pathsSection": "경로",
    "settings.sourceLabel": "입력 폴더",
    "settings.outputLabel": "출력 폴더",
    "generate.finalize": "일기 생성",
    "generate.draft": "초안 갱신",
    "generate.todayFinalize": "오늘 기록 생성",
    "generate.todayDraft": "오늘 초안 갱신",
    "generate.connect": "Codex 연결 후 생성",
    "generate.connectTitle": "먼저 Codex를 연결해야 생성할 수 있어요.",
    "generate.cancel": "취소",
    "generate.cancelling": "취소 중...",
    "generate.cancelTitle": "현재 생성 작업을 취소해요.",
    "generate.busy": "생성 중...",
    "loading.badge": "{{language}}로 만드는 중",
    "loading.titleWithDate": "{{date}} 기록을 차분히 엮고 있어요",
    "loading.titleToday": "오늘 기록을 차분히 엮고 있어요",
    "loading.copy":
      "잠깐만 기다려 주세요. 오늘 화면에 남은 기록을 모아 일기와 보고서로 다듬고, 준비되면 바로 여기서 열어 줄게요.",
    "loading.step.collect": "Chronicle 요약 읽기",
    "loading.step.organize": "하루 흐름 시간순 정리",
    "loading.step.write": "Codex로 초안 만들기",
    "loading.step.finish": "앱 안에서 바로 열 수 있게 다듬기",
    "loading.detail.collect": "먼저 오늘의 Markdown 요약을 모으고 있어요.",
    "loading.detail.organize": "겹치는 내용을 덜고 시간을 맞춰 흐름을 세우고 있어요.",
    "loading.detail.write": "보이는 사실만 바탕으로 작업 일기 초안을 만들고 있어요.",
    "loading.detail.writePrepare": "오늘 맥락을 Codex에 넘길 수 있게 묶고 있어요.",
    "loading.detail.writeStart": "Codex 초안 생성을 시작하고 있어요.",
    "loading.detail.writeWait": "Codex가 초안을 마칠 때까지 기다리고 있어요.",
    "loading.detail.writeCheck": "생성된 Markdown 결과를 확인하고 있어요.",
    "loading.detail.writeReady": "초안을 앱으로 다시 가져오고 있어요.",
    "loading.detail.cancel": "지금 생성 중인 초안을 멈추고 있어요.",
    "loading.detail.cancelled": "생성을 취소했어요.",
    "loading.detail.finish": "결과를 앱 안에서 바로 열 수 있게 정리하고 있어요.",
    "loading.elapsed": "{{seconds}}초 경과",
    "loading.meta": "완료되면 이 자리에서 바로 열려요.",
    "loading.meta.slow": "기록이 많은 날이나 매우 길게는 4~5분 정도 걸릴 수 있어요. 준비되면 알림으로 알려드릴게요.",
    "path.default": "기본 폴더 사용",
    "boundary.label": "{{hour}}시",
    "boundary.chip": "{{hour}}시 기준",
    "empty.report": "아직 보고서 내용이 없어요.",
    "empty.diary": "표시할 일기가 아직 없어요.",
    "empty.titleWithDate": "{{date}} 기록을 만들어 볼까요?",
    "empty.titleToday": "오늘을 조용히 기록해 볼까요?",
    "empty.copyWithDate":
      "이 날짜는 아직 저장된 일기가 없어요. 생성 버튼을 누르면 {{language}} 결과로 바로 생성돼요.",
    "empty.copyToday": "생성 버튼을 누르면 Chronicle 요약이 보고서와 일기로 다정하게 정리돼요.",
    "diary.title": "오늘의 일기",
    "mood.label": "오늘의 기분",
    "summary.label": "오늘의 한 줄 요약",
    "memo.placeholder": "오늘 떠오른 짧은 메모를 적어 두세요.",
    "memo.save": "저장하기",
    "memo.saved": "메모를 저장했어요",
    "foot.saved": "자동 저장됨",
    "foot.preview": "미리보기",
    "foot.modeFinalize": "최종 일기",
    "foot.modeDraft": "초안 갱신",
    "foot.writtenAt": "작성 시간",
    "report.today": "오늘 한 일",
    "report.highlights": "오늘의 하이라이트",
    "report.blockers": "막혔던 점",
    "report.tomorrow": "내일 할 일",
    "report.reflection": "짧은 회고",
    "carryover.title": "이어받은 할 일",
    "carryover.subtitle": "{{count}}개가 오늘 목록에 있어요",
    "carryover.from": "{{date}}에서 넘겨둠",
    "todo.carryForward": "내일 목록에 추가",
    "todo.carriedForward": "이미 내일 목록에 있어요",
    "todo.markDone": "완료로 표시",
    "todo.markOpen": "다시 열어두기",
    "timeline.title": "시간순 흐름",
    "timeline.more": "{{count}}개 더 보기",
    "timeline.all": "전체 펼치기 ({{count}})",
    "timeline.collapse": "전체 접기",
    "timeline.status": "지금 {{visible}}개를 보고 있어요 · {{remaining}}개가 더 남아 있어요",
    "calendar.savedCount": "저장 {{count}}개",
    "calendar.weekSection": "주간 모음",
    "calendar.weekRecords": "{{count}}개 기록",
    "archive.eyebrow": "보관함",
    "archive.title": "날짜별 기록과 주간 묶음을 한곳에서",
    "archive.copy": "사이드바는 가볍게 두고, 저장된 일기 탐색은 넓은 메인 화면에서 보도록 정리했어요.",
    "archive.recentSection": "최근 날짜 · {{count}}개",
    "archive.weeklySection": "주간 묶음 · {{count}}개",
    "archive.emptyDaily": "아직 저장된 일기가 없어요.",
    "archive.emptyWeekly": "주간 묶음이 아직 없어요.",
    "side.emptyDaily": "아직 저장된 일기가 없어요",
    "side.emptyWeekly": "주간 묶음은 아직 없어요",
    "saved.diary": "저장된 일기",
    "saved.records": "{{count}}개 기록",
    "status.text.connected": "Codex 준비됨",
    "status.text.connect": "Codex 연결",
    "status.text.check": "Codex 확인",
    "status.text.loading": "Codex 확인 중",
    "status.action.connect": "연결",
    "status.action.check": "확인",
    "status.modelLabel": "Codex 모델",
    "status.detail.connected": "일기 생성 준비가 끝났어요.",
    "status.detail.login": "로그인이 필요해요.",
    "status.detail.wait": "잠시만 기다려 주세요.",
    "connect.badge": "Codex",
    "connect.title": "먼저 Codex를 연결해주세요",
    "connect.body.connected": "Codex 연결 상태가 정상이라서, 이제 날짜를 고르면 바로 생성할 수 있어요.",
    "connect.body.default": "먼저 Codex 로그인 상태를 확인해야 해요.",
    "readiness.title": "생성 전 확인",
    "readiness.prereqTitle": "Chronicle 요약이 필요해요",
    "readiness.prereqBody":
      "Codex Diary는 화면 녹화나 스크린샷을 직접 읽지 않아요. 먼저 Chronicle을 켜서 Markdown 요약을 만들고, 그 요약 폴더를 입력 폴더로 사용해 주세요.",
    "readiness.sourceCount": "Markdown {{count}}개",
    "readiness.sourceMissing": "Chronicle 요약 폴더를 찾지 못했어요",
    "readiness.sourceEmpty": "Chronicle Markdown 요약이 아직 없어요",
    "readiness.outputReady": "준비됨",
    "readiness.outputMissing": "저장할 때 자동으로 만들어요",
    "footer.ready": "날짜를 고르고 기록을 생성하면 앱 안에서 바로 일기와 보고서를 볼 수 있어요.",
    "footer.connectFirst": "먼저 Codex를 연결해 주세요.",
    "footer.generating": "Chronicle 요약을 읽고 선택한 날짜의 기록을 {{language}}로 만드는 중이에요...",
    "footer.cancelling": "지금 생성 중인 작업을 취소하고 있어요...",
    "footer.cancelled": "생성을 취소했어요.",
    "footer.generateFailed": "생성에 실패했어요.",
    "footer.connected": "날짜를 고르고 기록을 생성하면 앱 안에서 바로 일기와 보고서를 볼 수 있어요.",
    "footer.rechecked": "Codex 연결 상태를 다시 확인했어요.",
    "footer.connectFailed": "Codex 연결에 실패했어요.",
    "footer.noSavedForDate":
      "{{date}} 저장된 일기가 아직 없어요. 새로 생성하면 이 날짜 기록으로 덮어써집니다.",
    "footer.noSavedForDateCalendar":
      "{{date}} 저장된 일기가 아직 없어요. 생성하면 {{language}} 결과로 저장돼요.",
    "footer.openDiaryFailed": "{{date}} 일기를 열 수 없어요.",
    "footer.openedDiary": "{{date}} 일기를 열었어요.",
    "footer.openWeekFailed": "주간 보기를 열 수 없어요.",
    "footer.openedWeek": "{{label}} 주간 보기를 열었어요.",
    "footer.calendarHint": "캘린더 탭에서 날짜를 골라 기록을 이어서 볼 수 있어요.",
    "footer.generated": "{{date}} 일기를 {{language}}로 바로 열었어요.{{saved}}",
    "toast.codexReady": "Codex 준비 완료",
    "toast.sourceChanged": "입력 폴더를 바꿨어요",
    "toast.outputChanged": "출력 폴더를 바꿨어요",
    "toast.nothingToCopy": "복사할 내용이 없어요",
    "toast.copied": "복사했어요",
    "toast.copyFailed": "복사에 실패했어요",
    "toast.noSavedFile": "저장된 파일이 없어요",
    "toast.openExternalFailed": "저장된 파일을 열지 못했어요",
    "toast.cancelled": "생성을 취소했어요",
    "toast.todayAdjusted": "오늘 기준 날짜로 맞췄어요",
    "toast.languageChanged": "언어를 {{language}}로 바꿨어요",
    "toast.lengthChanged": "일기 길이를 {{length}}로 바꿨어요",
    "toast.modelChanged": "Codex 모델을 {{model}}로 바꿨어요",
    "toast.todoCarried": "{{date}} 할 일 목록에 추가했어요",
    "toast.todoAlreadyCarried": "이미 {{date}} 할 일 목록에 있어요",
    "toast.todoUpdated": "할 일 상태를 바꿨어요",
    "warning.webview": "WebView 브리지가 준비되지 않았어요.",
    "warning.timeout": "응답이 {{seconds}}초 넘게 걸리고 있어요. 긴 날은 4~5분 정도 걸릴 수 있지만, 이번 실행은 다시 시도하는 편이 좋을 수 있어요.",
    "length.short": "짧게",
    "length.medium": "중간",
    "length.long": "길게",
    "length.very-long": "매우 길게",
    "tag.today": "오늘기록",
    "tag.decisions": "결정",
    "tag.blockers": "고민",
    "tag.tomorrow": "내일할일",
    "tag.diary": "일기",
    "mood.sparkle": "반짝",
    "mood.happy": "좋음",
    "mood.soft": "잔잔",
    "mood.tired": "지침",
    "mood.blue": "울적",
  },
  ja: {
    "brand.sub": "Chronicle の要約を日記に",
    "nav.diary": "日記",
    "nav.calendar": "カレンダー",
    "nav.archive": "保管庫",
    "side.recent": "最近の日付",
    "side.weekly": "週ごとの記録",
    "settings.title": "設定",
    "action.today": "今日へ",
    "view.diary": "日記",
    "view.report": "レポート",
    "menu.viewWeek": "この週を見る",
    "menu.copy": "現在の表示をコピー",
    "menu.external": "外部アプリで開く",
    "settings.languageLabel": "言語",
    "settings.boundaryLabel": "一日の区切り",
    "settings.modeLabel": "生成モード",
    "settings.modeFinalize": "最終日記",
    "settings.modeDraft": "下書きを更新",
    "settings.pathsSection": "パス",
    "settings.sourceLabel": "入力フォルダー",
    "settings.outputLabel": "出力フォルダー",
    "action.change": "変更",
    "loading.badge": "{{language}}で作成中",
    "loading.titleWithDate": "{{date}} の記録を静かにまとめています",
    "loading.titleToday": "今日の記録を静かにまとめています",
    "loading.copy": "Chronicle の要約を集め、時間順に整え、このアプリの中で読める日記とレポートにまとめています。",
    "loading.step.collect": "Chronicle 要約を読む",
    "loading.step.organize": "一日の流れを時系列で整理",
    "loading.step.write": "Codex に下書きを依頼",
    "loading.step.finish": "アプリ内表示向けに整える",
    "loading.detail.collect": "まず今日の Markdown 要約を集めています。",
    "loading.detail.organize": "重なりを減らし、流れを時間順に並べています。",
    "loading.detail.write": "見えていた事実だけで下書きを作っています。",
    "loading.detail.writePrepare": "今日の文脈を Codex に渡せる形にまとめています。",
    "loading.detail.writeStart": "Codex の下書き生成を開始しています。",
    "loading.detail.writeWait": "Codex が下書きを終えるまで待っています。",
    "loading.detail.writeCheck": "生成された Markdown 結果を確認しています。",
    "loading.detail.writeReady": "下書きをアプリに戻しています。",
    "loading.detail.finish": "この画面でそのまま開ける形に整えています。",
    "loading.elapsed": "{{seconds}}秒経過",
    "loading.meta": "完了するとここに自動で表示されます。",
    "diary.title": "今日の日記",
    "mood.label": "今日の気分",
    "summary.label": "今日の一行まとめ",
    "memo.save": "保存",
    "report.today": "今日やったこと",
    "report.highlights": "ハイライト",
    "report.blockers": "詰まった点",
    "report.tomorrow": "明日やること",
    "report.reflection": "短い振り返り",
    "timeline.title": "時系列の流れ",
    "calendar.weekSection": "週のまとめ",
    "archive.eyebrow": "保管庫",
    "archive.title": "日別記録と週ごとの束を一か所で",
    "side.emptyDaily": "保存された日記はまだありません",
    "side.emptyWeekly": "週の束はまだありません",
  },
  zh: {
    "brand.sub": "把 Chronicle 摘要变成日记",
    "nav.diary": "日记",
    "nav.calendar": "日历",
    "nav.archive": "归档",
    "side.recent": "最近日期",
    "side.weekly": "每周汇总",
    "settings.title": "设置",
    "action.today": "今天",
    "view.diary": "日记",
    "view.report": "报告",
    "menu.viewWeek": "查看本周",
    "menu.copy": "复制当前内容",
    "menu.external": "在外部应用中打开",
    "settings.languageLabel": "语言",
    "settings.boundaryLabel": "日期边界",
    "settings.modeLabel": "生成模式",
    "settings.modeFinalize": "最终日记",
    "settings.modeDraft": "更新草稿",
    "settings.pathsSection": "路径",
    "settings.sourceLabel": "输入文件夹",
    "settings.outputLabel": "输出文件夹",
    "action.change": "更改",
    "loading.badge": "正在生成为 {{language}}",
    "loading.titleWithDate": "正在安静整理 {{date}} 的记录",
    "loading.titleToday": "正在安静整理今天的记录",
    "loading.copy": "正在收集 Chronicle 摘要，按时间整理，并在应用内生成可直接阅读的日记和报告。",
    "loading.step.collect": "读取 Chronicle 摘要",
    "loading.step.organize": "按时间整理一天流程",
    "loading.step.write": "让 Codex 生成草稿",
    "loading.step.finish": "整理成应用内结果",
    "loading.detail.collect": "先收集今天的 Markdown 摘要。",
    "loading.detail.organize": "去掉重复内容并按时间排好。",
    "loading.detail.write": "只基于可见事实生成草稿。",
    "loading.detail.writePrepare": "正在整理今天的上下文，以便交给 Codex。",
    "loading.detail.writeStart": "正在启动 Codex 草稿生成。",
    "loading.detail.writeWait": "正在等待 Codex 完成草稿。",
    "loading.detail.writeCheck": "正在检查生成出的 Markdown 结果。",
    "loading.detail.writeReady": "正在把草稿返回到应用里。",
    "loading.detail.finish": "整理成可在这里直接打开的结果。",
    "loading.elapsed": "已过去 {{seconds}} 秒",
    "loading.meta": "完成后会自动显示在这里。",
    "diary.title": "今日日记",
    "mood.label": "今天的心情",
    "summary.label": "今日一句总结",
    "memo.save": "保存",
    "report.today": "今天做了什么",
    "report.highlights": "重点",
    "report.blockers": "阻碍",
    "report.tomorrow": "明天要做的事",
    "report.reflection": "简短回顾",
    "timeline.title": "时间线",
    "calendar.weekSection": "每周汇总",
    "archive.eyebrow": "归档",
    "archive.title": "在一个地方查看每日记录和每周合集",
    "side.emptyDaily": "还没有已保存的日记",
    "side.emptyWeekly": "还没有每周合集",
  },
  fr: {
    "brand.sub": "Transformer les resumes Chronicle en journal",
    "nav.diary": "Journal",
    "nav.calendar": "Calendrier",
    "nav.archive": "Archive",
    "side.recent": "Dates recentes",
    "side.weekly": "Semaines",
    "settings.title": "Parametres",
    "action.today": "Aujourd'hui",
    "view.diary": "Journal",
    "view.report": "Rapport",
    "menu.viewWeek": "Voir cette semaine",
    "menu.copy": "Copier la vue actuelle",
    "menu.external": "Ouvrir dans une app externe",
    "settings.languageLabel": "Langue",
    "settings.boundaryLabel": "Limite du jour",
    "settings.modeLabel": "Mode de generation",
    "settings.modeFinalize": "Journal final",
    "settings.modeDraft": "Mettre a jour le brouillon",
    "settings.pathsSection": "Chemins",
    "settings.sourceLabel": "Dossier source",
    "settings.outputLabel": "Dossier de sortie",
    "action.change": "Modifier",
    "loading.badge": "Creation en {{language}}",
    "loading.titleWithDate": "Assemblage doux du journal du {{date}}",
    "loading.titleToday": "Assemblage doux du journal du jour",
    "loading.copy": "Les resumes Chronicle sont rassembles, remis en ordre temporel et transformes en journal et rapport dans l'application.",
    "loading.step.collect": "Lire les resumes Chronicle",
    "loading.step.organize": "Ranger le fil de la journee",
    "loading.step.write": "Demander le brouillon a Codex",
    "loading.step.finish": "Finaliser le rendu dans l'app",
    "loading.detail.collect": "Je rassemble d'abord les resumes Markdown du jour.",
    "loading.detail.organize": "Je retire les recouvrements et je remets le flux dans l'ordre.",
    "loading.detail.write": "Je prepare un brouillon factuel via Codex.",
    "loading.detail.writePrepare": "Je prepare le contexte du jour pour Codex.",
    "loading.detail.writeStart": "Je lance la generation du brouillon par Codex.",
    "loading.detail.writeWait": "J'attends que Codex termine le brouillon.",
    "loading.detail.writeCheck": "Je verifie le resultat Markdown genere.",
    "loading.detail.writeReady": "Je renvoie le brouillon vers l'application.",
    "loading.detail.finish": "Je mets le resultat en forme pour l'ouvrir ici.",
    "loading.elapsed": "{{seconds}} s ecoulees",
    "loading.meta": "Le resultat apparaitra ici automatiquement.",
    "diary.title": "Journal du jour",
    "mood.label": "Humeur du jour",
    "summary.label": "Resume en une ligne",
    "memo.save": "Enregistrer",
    "report.today": "Ce que j'ai fait aujourd'hui",
    "report.highlights": "Points forts",
    "report.blockers": "Blocages",
    "report.tomorrow": "Demain",
    "report.reflection": "Courte retrospective",
    "timeline.title": "Chronologie",
    "calendar.weekSection": "Collections hebdomadaires",
    "archive.eyebrow": "Archive",
    "archive.title": "Parcourir les notes par jour et par semaine",
  },
  de: {
    "brand.sub": "Chronicle-Zusammenfassungen als Tagebuch",
    "nav.diary": "Tagebuch",
    "nav.calendar": "Kalender",
    "nav.archive": "Archiv",
    "side.recent": "Letzte Daten",
    "side.weekly": "Wochen",
    "settings.title": "Einstellungen",
    "action.today": "Heute",
    "view.diary": "Tagebuch",
    "view.report": "Bericht",
    "menu.viewWeek": "Diese Woche ansehen",
    "menu.copy": "Aktuelle Ansicht kopieren",
    "menu.external": "In externer App offnen",
    "settings.languageLabel": "Sprache",
    "settings.boundaryLabel": "Tagesgrenze",
    "settings.modeLabel": "Erzeugungsmodus",
    "settings.modeFinalize": "Finales Tagebuch",
    "settings.modeDraft": "Entwurf aktualisieren",
    "settings.pathsSection": "Pfade",
    "settings.sourceLabel": "Quellordner",
    "settings.outputLabel": "Ausgabeordner",
    "action.change": "Andern",
    "loading.badge": "Erstellung in {{language}}",
    "loading.titleWithDate": "{{date}} wird gerade sanft zum Tagebuch verwoben",
    "loading.titleToday": "Heute wird gerade sanft zum Tagebuch verwoben",
    "loading.copy": "Chronicle-Zusammenfassungen werden gesammelt, zeitlich sortiert und direkt in der App zu Tagebuch und Bericht geformt.",
    "loading.step.collect": "Chronicle-Zusammenfassungen lesen",
    "loading.step.organize": "Tagesablauf zeitlich sortieren",
    "loading.step.write": "Codex um den Entwurf bitten",
    "loading.step.finish": "Ergebnis fur die App aufbereiten",
    "loading.detail.collect": "Zuerst sammle ich die Markdown-Zusammenfassungen des Tages.",
    "loading.detail.organize": "Uberlappungen werden entfernt und zeitlich geordnet.",
    "loading.detail.write": "Ein sachlicher Entwurf wird uber Codex vorbereitet.",
    "loading.detail.writePrepare": "Der heutige Kontext wird fur Codex vorbereitet.",
    "loading.detail.writeStart": "Der Codex-Entwurf wird gestartet.",
    "loading.detail.writeWait": "Ich warte, bis Codex den Entwurf beendet.",
    "loading.detail.writeCheck": "Das erzeugte Markdown-Ergebnis wird gepruft.",
    "loading.detail.writeReady": "Der Entwurf wird zur App zuruckgegeben.",
    "loading.detail.finish": "Das Ergebnis wird so formatiert, dass es hier aufgeht.",
    "loading.elapsed": "{{seconds}} s vergangen",
    "loading.meta": "Das Ergebnis erscheint hier automatisch.",
    "diary.title": "Heutiges Tagebuch",
    "mood.label": "Heutige Stimmung",
    "summary.label": "Ein-Satz-Zusammenfassung",
    "memo.save": "Speichern",
    "report.today": "Was ich heute gemacht habe",
    "report.highlights": "Highlights",
    "report.blockers": "Blocker",
    "report.tomorrow": "Morgen",
    "report.reflection": "Kurze Reflexion",
    "timeline.title": "Zeitlicher Verlauf",
    "calendar.weekSection": "Wochensammlungen",
    "archive.eyebrow": "Archiv",
    "archive.title": "Tagesnotizen und Wochenbundel an einem Ort",
  },
  es: {
    "brand.sub": "Convierte los resumenes de Chronicle en diario",
    "nav.diary": "Diario",
    "nav.calendar": "Calendario",
    "nav.archive": "Archivo",
    "side.recent": "Fechas recientes",
    "side.weekly": "Semanas",
    "settings.title": "Configuracion",
    "action.today": "Hoy",
    "view.diary": "Diario",
    "view.report": "Informe",
    "menu.viewWeek": "Ver esta semana",
    "menu.copy": "Copiar vista actual",
    "menu.external": "Abrir en app externa",
    "settings.languageLabel": "Idioma",
    "settings.boundaryLabel": "Limite del dia",
    "settings.modeLabel": "Modo de generacion",
    "settings.modeFinalize": "Diario final",
    "settings.modeDraft": "Actualizar borrador",
    "settings.pathsSection": "Rutas",
    "settings.sourceLabel": "Carpeta de origen",
    "settings.outputLabel": "Carpeta de salida",
    "action.change": "Cambiar",
    "loading.badge": "Creando en {{language}}",
    "loading.titleWithDate": "Armando con calma el diario de {{date}}",
    "loading.titleToday": "Armando con calma el diario de hoy",
    "loading.copy": "Se estan reuniendo los resumenes de Chronicle, ordenandolos por tiempo y convirtiendolos en diario e informe dentro de la app.",
    "loading.step.collect": "Leer resumenes de Chronicle",
    "loading.step.organize": "Ordenar el flujo del dia",
    "loading.step.write": "Pedirle a Codex el borrador",
    "loading.step.finish": "Pulir el resultado en la app",
    "loading.detail.collect": "Primero se recopilan los resumenes Markdown del dia.",
    "loading.detail.organize": "Se quitan solapes y se ordenan los eventos por tiempo.",
    "loading.detail.write": "Se prepara un borrador factual con Codex.",
    "loading.detail.writePrepare": "Se prepara el contexto de hoy para Codex.",
    "loading.detail.writeStart": "Se inicia la generacion del borrador en Codex.",
    "loading.detail.writeWait": "Se espera a que Codex termine el borrador.",
    "loading.detail.writeCheck": "Se revisa el resultado Markdown generado.",
    "loading.detail.writeReady": "Se devuelve el borrador a la app.",
    "loading.detail.finish": "Se da formato para abrirlo aqui mismo.",
    "loading.elapsed": "{{seconds}} s transcurridos",
    "loading.meta": "Aparecera aqui automaticamente.",
    "diary.title": "Diario de hoy",
    "mood.label": "Estado de hoy",
    "summary.label": "Resumen en una linea",
    "memo.save": "Guardar",
    "report.today": "Lo que hice hoy",
    "report.highlights": "Aspectos clave",
    "report.blockers": "Bloqueos",
    "report.tomorrow": "Manana",
    "report.reflection": "Reflexion breve",
    "timeline.title": "Flujo cronologico",
    "calendar.weekSection": "Colecciones semanales",
    "archive.eyebrow": "Archivo",
    "archive.title": "Ver notas diarias y grupos semanales en un solo lugar",
  },
  vi: {
    "brand.sub": "Bien tong ket Chronicle thanh nhat ky",
    "nav.diary": "Nhat ky",
    "nav.calendar": "Lich",
    "nav.archive": "Luu tru",
    "side.recent": "Ngay gan day",
    "side.weekly": "Tong hop tuan",
    "settings.title": "Cai dat",
    "action.today": "Hom nay",
    "view.diary": "Nhat ky",
    "view.report": "Bao cao",
    "menu.viewWeek": "Xem tuan nay",
    "menu.copy": "Sao chep man hinh hien tai",
    "menu.external": "Mo bang ung dung ngoai",
    "settings.languageLabel": "Ngon ngu",
    "settings.boundaryLabel": "Moc ngay",
    "settings.modeLabel": "Che do tao",
    "settings.modeFinalize": "Nhat ky cuoi",
    "settings.modeDraft": "Cap nhat ban nhap",
    "settings.pathsSection": "Duong dan",
    "settings.sourceLabel": "Thu muc nguon",
    "settings.outputLabel": "Thu muc dau ra",
    "action.change": "Doi",
    "loading.badge": "Dang tao bang {{language}}",
    "loading.titleWithDate": "Dang nhe nhang ghep nhat ky cho {{date}}",
    "loading.titleToday": "Dang nhe nhang ghep nhat ky cho hom nay",
    "loading.copy": "Dang gom cac tom tat Chronicle, sap theo thoi gian va chuyen thanh nhat ky cung bao cao ngay trong ung dung.",
    "loading.step.collect": "Doc tom tat Chronicle",
    "loading.step.organize": "Sap xep dong chay trong ngay",
    "loading.step.write": "Nho Codex tao ban nhap",
    "loading.step.finish": "Hoan thien ket qua trong app",
    "loading.detail.collect": "Truoc het dang gom cac tom tat Markdown trong ngay.",
    "loading.detail.organize": "Dang bo phan trung lap va sap theo thu tu thoi gian.",
    "loading.detail.write": "Dang tao ban nhap dung theo nhung gi da thay bang Codex.",
    "loading.detail.writePrepare": "Dang gom ngu canh hom nay de gui cho Codex.",
    "loading.detail.writeStart": "Dang bat dau luot tao ban nhap voi Codex.",
    "loading.detail.writeWait": "Dang doi Codex hoan tat ban nhap.",
    "loading.detail.writeCheck": "Dang kiem tra ket qua Markdown vua tao.",
    "loading.detail.writeReady": "Dang dua ban nhap tro lai ung dung.",
    "loading.detail.finish": "Dang dinh dang de mo ngay tai day.",
    "loading.elapsed": "Da qua {{seconds}} giay",
    "loading.meta": "Xong la ket qua se hien ngay o day.",
    "diary.title": "Nhat ky hom nay",
    "mood.label": "Tam trang hom nay",
    "summary.label": "Tom tat mot dong",
    "memo.save": "Luu",
    "report.today": "Hom nay da lam gi",
    "report.highlights": "Diem nhan",
    "report.blockers": "Diem nghen",
    "report.tomorrow": "Ngay mai",
    "report.reflection": "Nhin lai ngan",
    "timeline.title": "Dong thoi gian",
    "calendar.weekSection": "Tong hop theo tuan",
    "archive.eyebrow": "Luu tru",
    "archive.title": "Xem ghi chu theo ngay va tuan tai mot noi",
  },
  th: {
    "brand.sub": "เปลี่ยนสรุป Chronicle ให้เป็นไดอารี",
    "nav.diary": "ไดอารี",
    "nav.calendar": "ปฏิทิน",
    "nav.archive": "คลัง",
    "side.recent": "วันที่ล่าสุด",
    "side.weekly": "สรุปรายสัปดาห์",
    "settings.title": "ตั้งค่า",
    "action.today": "วันนี้",
    "view.diary": "ไดอารี",
    "view.report": "รายงาน",
    "menu.viewWeek": "ดูสัปดาห์นี้",
    "menu.copy": "คัดลอกมุมมองปัจจุบัน",
    "menu.external": "เปิดในแอปภายนอก",
    "settings.languageLabel": "ภาษา",
    "settings.boundaryLabel": "เส้นแบ่งวัน",
    "settings.modeLabel": "โหมดการสร้าง",
    "settings.modeFinalize": "ไดอารีฉบับสุดท้าย",
    "settings.modeDraft": "อัปเดตร่าง",
    "settings.pathsSection": "เส้นทาง",
    "settings.sourceLabel": "โฟลเดอร์ต้นทาง",
    "settings.outputLabel": "โฟลเดอร์ผลลัพธ์",
    "action.change": "เปลี่ยน",
    "loading.badge": "กำลังสร้างเป็น {{language}}",
    "loading.titleWithDate": "กำลังค่อยๆ เรียบเรียงบันทึกของ {{date}}",
    "loading.titleToday": "กำลังค่อยๆ เรียบเรียงบันทึกของวันนี้",
    "loading.copy": "กำลังรวบรวมสรุป Chronicle จัดตามเวลา และเปลี่ยนเป็นไดอารีกับรายงานให้อ่านได้ในแอปนี้",
    "loading.step.collect": "อ่านสรุป Chronicle",
    "loading.step.organize": "จัดลำดับการไหลของวัน",
    "loading.step.write": "ให้ Codex เขียนร่าง",
    "loading.step.finish": "เกลาผลลัพธ์ในแอป",
    "loading.detail.collect": "กำลังรวบรวมสรุป Markdown ของวันนี้ก่อน",
    "loading.detail.organize": "กำลังตัดส่วนที่ซ้ำและเรียงตามเวลา",
    "loading.detail.write": "กำลังสร้างร่างจากข้อเท็จจริงที่มองเห็นได้ผ่าน Codex",
    "loading.detail.writePrepare": "กำลังจัดบริบทของวันนี้เพื่อส่งให้ Codex",
    "loading.detail.writeStart": "กำลังเริ่มให้ Codex สร้างร่าง",
    "loading.detail.writeWait": "กำลังรอให้ Codex เขียนร่างเสร็จ",
    "loading.detail.writeCheck": "กำลังตรวจผลลัพธ์ Markdown ที่สร้างขึ้น",
    "loading.detail.writeReady": "กำลังส่งร่างกลับเข้าแอป",
    "loading.detail.finish": "กำลังจัดรูปแบบให้เปิดได้ตรงนี้ทันที",
    "loading.elapsed": "ผ่านไป {{seconds}} วินาที",
    "loading.meta": "เสร็จแล้วผลลัพธ์จะขึ้นตรงนี้อัตโนมัติ",
    "diary.title": "ไดอารีของวันนี้",
    "mood.label": "อารมณ์วันนี้",
    "summary.label": "สรุปหนึ่งบรรทัด",
    "memo.save": "บันทึก",
    "report.today": "วันนี้ทำอะไรบ้าง",
    "report.highlights": "ไฮไลต์",
    "report.blockers": "จุดที่ติด",
    "report.tomorrow": "พรุ่งนี้",
    "report.reflection": "ทบทวนสั้นๆ",
    "timeline.title": "ลำดับเวลา",
    "calendar.weekSection": "ชุดรายสัปดาห์",
    "archive.eyebrow": "คลัง",
    "archive.title": "ดูบันทึกรายวันและรายสัปดาห์ในที่เดียว",
  },
  ru: {
    "brand.sub": "Превращайте сводки Chronicle в дневник",
    "nav.diary": "Дневник",
    "nav.calendar": "Календарь",
    "nav.archive": "Архив",
    "side.recent": "Последние даты",
    "side.weekly": "Недельные подборки",
    "settings.title": "Настройки",
    "action.today": "Сегодня",
    "view.diary": "Дневник",
    "view.report": "Отчет",
    "menu.viewWeek": "Открыть эту неделю",
    "menu.copy": "Копировать текущий вид",
    "menu.external": "Открыть во внешнем приложении",
    "settings.languageLabel": "Язык",
    "settings.boundaryLabel": "Граница дня",
    "settings.modeLabel": "Режим генерации",
    "settings.modeFinalize": "Итоговый дневник",
    "settings.modeDraft": "Обновить черновик",
    "settings.pathsSection": "Пути",
    "settings.sourceLabel": "Папка источника",
    "settings.outputLabel": "Папка вывода",
    "action.change": "Изменить",
    "loading.badge": "Создание на {{language}}",
    "loading.titleWithDate": "Спокойно собираю дневник за {{date}}",
    "loading.titleToday": "Спокойно собираю дневник за сегодня",
    "loading.copy": "Сводки Chronicle собираются, выстраиваются по времени и превращаются в дневник и отчет прямо в приложении.",
    "loading.step.collect": "Читаю сводки Chronicle",
    "loading.step.organize": "Упорядочиваю ход дня",
    "loading.step.write": "Прошу Codex сделать черновик",
    "loading.step.finish": "Довожу результат для приложения",
    "loading.detail.collect": "Сначала собираю сегодняшние Markdown-сводки.",
    "loading.detail.organize": "Убираю повторы и выстраиваю события по времени.",
    "loading.detail.write": "Готовлю фактический черновик через Codex.",
    "loading.detail.writePrepare": "Готовлю сегодняшний контекст для Codex.",
    "loading.detail.writeStart": "Запускаю создание черновика в Codex.",
    "loading.detail.writeWait": "Жду, пока Codex закончит черновик.",
    "loading.detail.writeCheck": "Проверяю сгенерированный Markdown.",
    "loading.detail.writeReady": "Возвращаю черновик обратно в приложение.",
    "loading.detail.finish": "Оформляю так, чтобы результат открылся прямо здесь.",
    "loading.elapsed": "Прошло {{seconds}} с",
    "loading.meta": "Результат автоматически появится здесь.",
    "diary.title": "Дневник за сегодня",
    "mood.label": "Настроение сегодня",
    "summary.label": "Краткое резюме",
    "memo.save": "Сохранить",
    "report.today": "Что я сделал сегодня",
    "report.highlights": "Главное",
    "report.blockers": "Блокеры",
    "report.tomorrow": "Завтра",
    "report.reflection": "Короткая рефлексия",
    "timeline.title": "Хронология",
    "calendar.weekSection": "Недельные подборки",
    "archive.eyebrow": "Архив",
    "archive.title": "Просматривайте дневные записи и недельные подборки в одном месте",
  },
  hi: {
    "brand.sub": "Chronicle सारांश को डायरी में बदलें",
    "nav.diary": "डायरी",
    "nav.calendar": "कैलेंडर",
    "nav.archive": "संग्रह",
    "side.recent": "हाल की तिथियां",
    "side.weekly": "साप्ताहिक संग्रह",
    "settings.title": "सेटिंग्स",
    "action.today": "आज",
    "view.diary": "डायरी",
    "view.report": "रिपोर्ट",
    "menu.viewWeek": "इस सप्ताह को देखें",
    "menu.copy": "मौजूदा दृश्य कॉपी करें",
    "menu.external": "बाहरी ऐप में खोलें",
    "settings.languageLabel": "भाषा",
    "settings.boundaryLabel": "दिन की सीमा",
    "settings.modeLabel": "जनरेशन मोड",
    "settings.modeFinalize": "अंतिम डायरी",
    "settings.modeDraft": "ड्राफ्ट अपडेट करें",
    "settings.pathsSection": "पथ",
    "settings.sourceLabel": "स्रोत फोल्डर",
    "settings.outputLabel": "आउटपुट फोल्डर",
    "action.change": "बदलें",
    "loading.badge": "{{language}} में बना रहे हैं",
    "loading.titleWithDate": "{{date}} की डायरी को धीरे-धीरे बुन रहे हैं",
    "loading.titleToday": "आज की डायरी को धीरे-धीरे बुन रहे हैं",
    "loading.copy": "Chronicle सारांश इकट्ठा किए जा रहे हैं, समय के अनुसार सजाए जा रहे हैं, और इसी ऐप में डायरी व रिपोर्ट में बदले जा रहे हैं।",
    "loading.step.collect": "Chronicle सारांश पढ़ना",
    "loading.step.organize": "दिन के प्रवाह को समयानुसार जमाना",
    "loading.step.write": "Codex से ड्राफ्ट बनवाना",
    "loading.step.finish": "ऐप के लिए परिणाम संवारना",
    "loading.detail.collect": "पहले आज के Markdown सारांश इकट्ठा किए जा रहे हैं।",
    "loading.detail.organize": "दोहराव हटाकर घटनाओं को समयानुसार जमाया जा रहा है।",
    "loading.detail.write": "सिर्फ दिखे हुए तथ्यों पर आधारित ड्राफ्ट तैयार हो रहा है।",
    "loading.detail.writePrepare": "आज के संदर्भ को Codex के लिए तैयार किया जा रहा है।",
    "loading.detail.writeStart": "Codex में ड्राफ्ट बनाना शुरू किया जा रहा है।",
    "loading.detail.writeWait": "Codex के ड्राफ्ट पूरा करने का इंतजार है।",
    "loading.detail.writeCheck": "बने हुए Markdown नतीजे की जांच की जा रही है।",
    "loading.detail.writeReady": "ड्राफ्ट को वापस ऐप में लाया जा रहा है।",
    "loading.detail.finish": "परिणाम को यहीं खोलने लायक रूप दिया जा रहा है।",
    "loading.elapsed": "{{seconds}} सेकंड बीत गए",
    "loading.meta": "पूरा होते ही नतीजा यहीं दिखाई देगा।",
    "diary.title": "आज की डायरी",
    "mood.label": "आज का मूड",
    "summary.label": "एक पंक्ति सार",
    "memo.save": "सहेजें",
    "report.today": "आज मैंने क्या किया",
    "report.highlights": "मुख्य बातें",
    "report.blockers": "अटके हुए बिंदु",
    "report.tomorrow": "कल",
    "report.reflection": "छोटी समीक्षा",
    "timeline.title": "समय प्रवाह",
    "calendar.weekSection": "साप्ताहिक संग्रह",
    "archive.eyebrow": "संग्रह",
    "archive.title": "दैनिक नोट्स और साप्ताहिक समूह एक ही जगह देखें",
  },
};
