(function installUiCopyLocales() {
  const copy = window.CODEX_DIARY_UI_COPY;
  if (!copy) return;

  const complements = {
    ja: {
      "app.title": "Codex Diary",
      "quote.html": "毎日の記録が<br />明日の私をつくる <span class=\"heart\">♡</span>",
      "date.label": "基準日",
      "date.missing": "日付を選んでください",
      "action.prevDay": "前日",
      "action.nextDay": "翌日",
      "action.pickDate": "日付を選ぶ",
      "action.more": "もっと見る",
      "action.close": "閉じる",
      "view.raw": "Markdown",
      "settings.panelAria": "設定パネル",
      "settings.eyebrow": "環境設定",
      "settings.summaryAria": "設定の概要",
      "settings.summaryStrong": "記録の流れを自分のリズムに合わせられます。",
      "settings.summaryCopy":
        "言語、日付の区切り時刻、保存方法を先に整えておくと、毎日同じリズムで日記を作れます。",
      "settings.introBadge": "既定の言語: {{language}}",
      "settings.outputSection": "出力",
      "settings.languageHint": "生成される日記とアプリ UI の両方がこの言語にそろいます。",
      "settings.lengthLabel": "日記の長さ",
      "settings.lengthHint": "生成される日記の分量を短めからかなり長めまで選べます。",
      "settings.boundaryHint": "この時刻より前の記録は前日の日記にまとめられます。",
      "settings.autoSaveTitle": "生成後に自動保存する",
      "settings.autoSaveHint": "生成した結果をすぐに出力フォルダーへ保存します。",
      "generate.finalize": "日記を作成",
      "generate.draft": "下書きを更新",
      "generate.todayFinalize": "今日の記録を作成",
      "generate.todayDraft": "今日の下書きを更新",
      "generate.connect": "Codex 接続後に作成",
      "generate.connectTitle": "生成する前に Codex を接続してください。",
      "generate.cancel": "キャンセル",
      "generate.cancelling": "キャンセル中...",
      "generate.cancelTitle": "現在の生成をキャンセルします。",
      "generate.busy": "生成中...",
      "loading.detail.cancel": "現在の下書き生成を停止しています。",
      "loading.detail.cancelled": "生成をキャンセルしました。",
      "loading.meta.slow":
        "記録が多い日や「とても長い」は 4〜5 分ほどかかることがあります。準備ができたら通知します。",
      "path.default": "既定フォルダーを使う",
      "boundary.label": "{{hour}}:00",
      "boundary.chip": "{{hour}}時基準",
      "empty.report": "まだレポートはありません。",
      "empty.diary": "表示できる日記がまだありません。",
      "empty.titleWithDate": "{{date}} の記録を作りますか？",
      "empty.titleToday": "今日をそっと残してみますか？",
      "empty.copyWithDate":
        "この日付にはまだ保存された日記がありません。生成ボタンを押すと {{language}} ですぐに作成されます。",
      "empty.copyToday": "生成ボタンを押すと、Chronicle の要約からレポートと日記が一緒に作られます。",
      "memo.placeholder": "今日のうちに残しておきたい短いメモを書いてください。",
      "memo.saved": "メモを保存しました。",
      "foot.saved": "自動保存済み",
      "foot.preview": "プレビュー",
      "foot.modeFinalize": "最終日記",
      "foot.modeDraft": "下書き更新",
      "foot.writtenAt": "作成時刻",
      "carryover.title": "今日へ持ち越したこと",
      "carryover.subtitle": "{{count}} 件のタスクがここで待っています",
      "carryover.from": "{{date}} から",
      "todo.carryForward": "明日に回す",
      "todo.carriedForward": "すでに明日に追加済み",
      "todo.markDone": "完了にする",
      "todo.markOpen": "未完了に戻す",
      "timeline.more": "{{count}} 件もっと見る",
      "timeline.all": "すべて開く ({{count}})",
      "timeline.collapse": "すべて閉じる",
      "timeline.status": "現在 {{visible}} 件表示中 · あと {{remaining}} 件",
      "calendar.savedCount": "{{count}} 件保存済み",
      "calendar.weekRecords": "{{count}} 件の記録",
      "archive.copy": "サイドバーは軽く保ち、保存済みの日記はメイン領域でゆっくり見返せます。",
      "archive.recentSection": "最近の日付 · {{count}}",
      "archive.weeklySection": "週ごとの束 · {{count}}",
      "archive.emptyDaily": "保存された日記はまだありません。",
      "archive.emptyWeekly": "週ごとの束はまだありません。",
      "saved.diary": "保存済みの日記",
      "saved.records": "{{count}} 件の記録",
      "status.text.connected": "Codex 準備完了",
      "status.text.connect": "Codex 接続",
      "status.text.check": "Codex 確認",
      "status.text.loading": "Codex を確認中",
      "status.action.connect": "接続",
      "status.action.check": "確認",
      "status.modelLabel": "Codex モデル",
      "status.detail.connected": "すぐに日記を作れる状態です。",
      "status.detail.login": "ログインが必要です。",
      "status.detail.wait": "少し待ってください。",
      "connect.badge": "Codex",
      "connect.title": "先に Codex を接続してください",
      "connect.body.connected": "Codex の準備ができているので、日付を選ぶだけですぐに記録を作れます。",
      "connect.body.default": "まず Codex のログイン状態を確認してください。",
      "footer.ready": "日付を選んで記録を作ると、このアプリの中で日記とレポートをすぐに読めます。",
      "footer.connectFirst": "先に Codex を接続してください。",
      "footer.generating": "Chronicle の要約を読み込み、選んだ日の記録を {{language}} で作成しています...",
      "footer.cancelling": "現在の生成をキャンセルしています...",
      "footer.cancelled": "生成をキャンセルしました。",
      "footer.generateFailed": "生成に失敗しました。",
      "footer.connected": "日付を選んで記録を作ると、このアプリの中で日記とレポートをすぐに読めます。",
      "footer.rechecked": "Codex の接続状態をもう一度確認しました。",
      "footer.connectFailed": "Codex への接続に失敗しました。",
      "footer.noSavedForDate": "{{date}} の保存済み日記はまだありません。もう一度生成するとその日の記録を上書きします。",
      "footer.noSavedForDateCalendar":
        "{{date}} の保存済み日記はまだありません。生成すると {{language}} で保存されます。",
      "footer.openDiaryFailed": "{{date}} の日記を開けませんでした。",
      "footer.openedDiary": "{{date}} の日記を開きました。",
      "footer.openWeekFailed": "週表示を開けませんでした。",
      "footer.openedWeek": "{{label}} の週表示を開きました。",
      "footer.calendarHint": "カレンダータブで日付を選んで、そのまま続けてください。",
      "footer.generated": "{{date}} の日記を {{language}} で開きました。{{saved}}",
      "toast.codexReady": "Codex の準備ができました",
      "toast.sourceChanged": "入力フォルダーを更新しました",
      "toast.outputChanged": "出力フォルダーを更新しました",
      "toast.nothingToCopy": "コピーできる内容がありません",
      "toast.copied": "コピーしました",
      "toast.copyFailed": "コピーに失敗しました",
      "toast.noSavedFile": "保存されたファイルがありません。",
      "toast.openExternalFailed": "保存ファイルを開けませんでした。",
      "toast.cancelled": "キャンセルしました",
      "toast.todayAdjusted": "今日の基準日へ移動しました",
      "toast.languageChanged": "言語を {{language}} に切り替えました",
      "toast.lengthChanged": "日記の長さを {{length}} に切り替えました",
      "toast.modelChanged": "Codex モデルを {{model}} に切り替えました",
      "toast.todoCarried": "{{date}} に追加しました。",
      "toast.todoAlreadyCarried": "すでに {{date}} に追加されています。",
      "toast.todoUpdated": "タスクを更新しました。",
      "warning.webview": "WebView ブリッジの準備ができていません。",
      "warning.timeout":
        "応答が {{seconds}} 秒を超えています。記録が多い日は 4〜5 分ほどかかることがありますが、この実行はやり直しが必要かもしれません。",
      "length.short": "短め",
      "length.medium": "標準",
      "length.long": "長め",
      "length.very-long": "とても長い",
      "tag.today": "今日",
      "tag.decisions": "決定",
      "tag.blockers": "詰まり",
      "tag.tomorrow": "明日",
      "tag.diary": "日記",
      "mood.sparkle": "きらきら",
      "mood.happy": "うれしい",
      "mood.soft": "穏やか",
      "mood.tired": "疲れた",
      "mood.blue": "しょんぼり",
    },
    zh: {
      "app.title": "Codex Diary",
      "quote.html": "每天的记录<br />会慢慢塑造明天 <span class=\"heart\">♡</span>",
      "date.label": "基准日期",
      "date.missing": "请选择日期",
      "action.prevDay": "前一天",
      "action.nextDay": "后一天",
      "action.pickDate": "选择日期",
      "action.more": "更多",
      "action.close": "关闭",
      "view.raw": "Markdown",
      "settings.panelAria": "设置面板",
      "settings.eyebrow": "偏好设置",
      "settings.summaryAria": "设置摘要",
      "settings.summaryStrong": "可以把记录节奏调成更适合自己的方式。",
      "settings.summaryCopy": "先设定语言、日期边界时间和保存方式后，每天就能用同样的节奏生成日记。",
      "settings.introBadge": "默认语言: {{language}}",
      "settings.outputSection": "语言与输出",
      "settings.languageHint": "生成结果和应用界面都会一起跟随这个语言。",
      "settings.lengthLabel": "日记长度",
      "settings.lengthHint": "可以从简短到非常详细，选择想要的生成篇幅。",
      "settings.boundaryHint": "这个时间之前的记录会归到前一天的日记里。",
      "settings.autoSaveTitle": "生成后自动保存",
      "settings.autoSaveHint": "生成完成后立刻保存到输出文件夹。",
      "generate.finalize": "生成日记",
      "generate.draft": "更新草稿",
      "generate.todayFinalize": "生成今天的记录",
      "generate.todayDraft": "更新今天的草稿",
      "generate.connect": "连接 Codex 后生成",
      "generate.connectTitle": "请先连接 Codex 再生成。",
      "generate.cancel": "取消",
      "generate.cancelling": "正在取消...",
      "generate.cancelTitle": "取消当前生成任务。",
      "generate.busy": "生成中...",
      "loading.detail.cancel": "正在停止当前草稿生成。",
      "loading.detail.cancelled": "生成已取消。",
      "loading.meta.slow": "记录较多的日期或“非常长”模式可能需要 4 到 5 分钟。准备好后会通知你。",
      "path.default": "使用默认文件夹",
      "boundary.label": "{{hour}}:00",
      "boundary.chip": "{{hour}}点基准",
      "empty.report": "还没有可显示的报告。",
      "empty.diary": "还没有可显示的日记。",
      "empty.titleWithDate": "要为 {{date}} 生成一篇记录吗？",
      "empty.titleToday": "要轻轻记下今天吗？",
      "empty.copyWithDate": "这个日期还没有已保存的日记。点击生成按钮后，会立即按 {{language}} 生成。",
      "empty.copyToday": "点击生成按钮后，Chronicle 摘要会同时整理成报告和日记。",
      "memo.placeholder": "写下一句今天想留下的简短备注。",
      "memo.saved": "备注已保存。",
      "foot.saved": "已自动保存",
      "foot.preview": "预览",
      "foot.modeFinalize": "最终日记",
      "foot.modeDraft": "草稿更新",
      "foot.writtenAt": "生成时间",
      "carryover.title": "延续到今天的事项",
      "carryover.subtitle": "这里还有 {{count}} 个任务在等你",
      "carryover.from": "来自 {{date}}",
      "todo.carryForward": "加入明天",
      "todo.carriedForward": "已加入明天",
      "todo.markDone": "标记完成",
      "todo.markOpen": "标记未完成",
      "timeline.more": "再显示 {{count}} 条",
      "timeline.all": "全部展开 ({{count}})",
      "timeline.collapse": "全部收起",
      "timeline.status": "当前显示 {{visible}} 条 · 还有 {{remaining}} 条",
      "calendar.savedCount": "已保存 {{count}} 条",
      "calendar.weekRecords": "{{count}} 条记录",
      "archive.copy": "侧边栏保持轻量，已保存的日记可以在主区域里慢慢查看。",
      "archive.recentSection": "最近日期 · {{count}}",
      "archive.weeklySection": "每周合集 · {{count}}",
      "archive.emptyDaily": "还没有已保存的日记。",
      "archive.emptyWeekly": "还没有每周合集。",
      "saved.diary": "已保存的日记",
      "saved.records": "{{count}} 条记录",
      "status.text.connected": "Codex 已就绪",
      "status.text.connect": "连接 Codex",
      "status.text.check": "检查 Codex",
      "status.text.loading": "正在检查 Codex",
      "status.action.connect": "连接",
      "status.action.check": "检查",
      "status.modelLabel": "Codex 模型",
      "status.detail.connected": "现在可以直接生成日记了。",
      "status.detail.login": "需要先登录。",
      "status.detail.wait": "请稍等一下。",
      "connect.badge": "Codex",
      "connect.title": "请先连接 Codex",
      "connect.body.connected": "Codex 已准备好，只要选一个日期就能马上生成记录。",
      "connect.body.default": "请先确认 Codex 的登录状态。",
      "footer.ready": "选择一个日期并生成记录后，就可以直接在应用里阅读日记和报告。",
      "footer.connectFirst": "请先连接 Codex。",
      "footer.generating": "正在读取 Chronicle 摘要，并用 {{language}} 生成所选日期的记录...",
      "footer.cancelling": "正在取消当前生成...",
      "footer.cancelled": "已取消生成。",
      "footer.generateFailed": "生成失败。",
      "footer.connected": "选择一个日期并生成记录后，就可以直接在应用里阅读日记和报告。",
      "footer.rechecked": "已再次检查 Codex 连接状态。",
      "footer.connectFailed": "连接 Codex 失败。",
      "footer.noSavedForDate": "{{date}} 还没有已保存的日记。再次生成会覆盖这一天的记录。",
      "footer.noSavedForDateCalendar": "{{date}} 还没有已保存的日记。生成后会按 {{language}} 保存。",
      "footer.openDiaryFailed": "无法打开 {{date}} 的日记。",
      "footer.openedDiary": "已打开 {{date}} 的日记。",
      "footer.openWeekFailed": "无法打开本周视图。",
      "footer.openedWeek": "已打开 {{label}} 的周视图。",
      "footer.calendarHint": "请在日历标签里选择日期，然后从那里继续。",
      "footer.generated": "已用 {{language}} 打开 {{date}} 的日记。{{saved}}",
      "toast.codexReady": "Codex 已就绪",
      "toast.sourceChanged": "输入文件夹已更新",
      "toast.outputChanged": "输出文件夹已更新",
      "toast.nothingToCopy": "没有可复制的内容",
      "toast.copied": "已复制",
      "toast.copyFailed": "复制失败",
      "toast.noSavedFile": "没有已保存的文件。",
      "toast.openExternalFailed": "无法打开已保存的文件。",
      "toast.cancelled": "已取消",
      "toast.todayAdjusted": "已跳到今天的有效日期",
      "toast.languageChanged": "语言已切换为 {{language}}",
      "toast.lengthChanged": "日记长度已切换为 {{length}}",
      "toast.modelChanged": "Codex 模型已切换为 {{model}}",
      "toast.todoCarried": "已加入 {{date}}。",
      "toast.todoAlreadyCarried": "已经加入 {{date}} 了。",
      "toast.todoUpdated": "任务已更新。",
      "warning.webview": "WebView 桥接尚未准备好。",
      "warning.timeout": "响应时间已超过 {{seconds}} 秒。记录较多的日期可能需要 4 到 5 分钟，但这次运行可能需要重试。",
      "length.short": "简短",
      "length.medium": "中等",
      "length.long": "较长",
      "length.very-long": "非常长",
      "tag.today": "今天",
      "tag.decisions": "决定",
      "tag.blockers": "阻碍",
      "tag.tomorrow": "明天",
      "tag.diary": "日记",
      "mood.sparkle": "闪闪发亮",
      "mood.happy": "开心",
      "mood.soft": "平静",
      "mood.tired": "疲惫",
      "mood.blue": "低落",
    },
    fr: {
      "app.title": "Codex Diary",
      "quote.html": "Les notes du jour<br />dessinent demain <span class=\"heart\">♡</span>",
      "date.label": "Date de reference",
      "date.missing": "Choisissez une date",
      "action.prevDay": "Jour precedent",
      "action.nextDay": "Jour suivant",
      "action.pickDate": "Choisir la date",
      "action.more": "Plus",
      "action.close": "Fermer",
      "view.raw": "Markdown",
      "settings.panelAria": "Panneau des parametres",
      "settings.eyebrow": "Preferences",
      "settings.summaryAria": "Resume des parametres",
      "settings.summaryStrong": "Ajustez le rythme du journal a votre facon.",
      "settings.summaryCopy":
        "Reglez d'abord la langue, la limite du jour et la sauvegarde pour garder une routine stable chaque jour.",
      "settings.introBadge": "Langue par defaut : {{language}}",
      "settings.outputSection": "Langue et sortie",
      "settings.languageHint": "La sortie du journal et l'interface de l'app suivent toutes les deux cette langue.",
      "settings.lengthLabel": "Longueur du journal",
      "settings.lengthHint": "Choisissez si le journal doit etre court, moyen ou tres detaille.",
      "settings.boundaryHint": "Les enregistrements avant cette heure sont ranges dans la veille.",
      "settings.autoSaveTitle": "Enregistrer automatiquement apres generation",
      "settings.autoSaveHint": "Sauvegarde le resultat tout de suite dans le dossier de sortie.",
      "generate.finalize": "Creer le journal",
      "generate.draft": "Mettre a jour le brouillon",
      "generate.todayFinalize": "Creer l'entree du jour",
      "generate.todayDraft": "Mettre a jour le brouillon du jour",
      "generate.connect": "Creer apres connexion a Codex",
      "generate.connectTitle": "Connectez Codex avant de generer.",
      "generate.cancel": "Annuler",
      "generate.cancelling": "Annulation...",
      "generate.cancelTitle": "Annuler la generation en cours.",
      "generate.busy": "Generation...",
      "loading.detail.cancel": "Arret de la generation du brouillon en cours.",
      "loading.detail.cancelled": "La generation a ete annulee.",
      "loading.meta.slow":
        "Les grosses journees ou le mode Tres long peuvent prendre 4 a 5 minutes. Une notification apparaitra des que ce sera pret.",
      "path.default": "Utiliser le dossier par defaut",
      "boundary.label": "{{hour}}:00",
      "boundary.chip": "Limite {{hour}}:00",
      "empty.report": "Aucun rapport n'est disponible pour l'instant.",
      "empty.diary": "Aucun journal n'est encore affiche.",
      "empty.titleWithDate": "Creer une entree pour le {{date}} ?",
      "empty.titleToday": "Envie de garder une trace douce d'aujourd'hui ?",
      "empty.copyWithDate":
        "Aucun journal enregistre n'existe encore pour cette date. Utilisez le bouton pour le generer tout de suite en {{language}}.",
      "empty.copyToday":
        "Utilisez le bouton de creation et les resumes Chronicle seront transformes a la fois en rapport et en journal.",
      "memo.placeholder": "Ecrivez une courte note que vous voulez garder de cette journee.",
      "memo.saved": "Votre note a ete enregistree.",
      "foot.saved": "Enregistre automatiquement",
      "foot.preview": "Apercu",
      "foot.modeFinalize": "Journal final",
      "foot.modeDraft": "Mise a jour du brouillon",
      "foot.writtenAt": "Ecrit a",
      "carryover.title": "Reporte a aujourd'hui",
      "carryover.subtitle": "{{count}} tache(s) vous attendent ici",
      "carryover.from": "Depuis le {{date}}",
      "todo.carryForward": "Ajouter a demain",
      "todo.carriedForward": "Deja ajoute a demain",
      "todo.markDone": "Marquer comme fait",
      "todo.markOpen": "Rouvrir",
      "timeline.more": "Afficher encore {{count}} elements",
      "timeline.all": "Tout developper ({{count}})",
      "timeline.collapse": "Tout replier",
      "timeline.status": "{{visible}} affiches maintenant · {{remaining}} restants",
      "calendar.savedCount": "{{count}} enregistre(s)",
      "calendar.weekRecords": "{{count}} entree(s)",
      "archive.copy": "Gardez la barre laterale legere et parcourez les journaux enregistres dans la zone principale.",
      "archive.recentSection": "Dates recentes · {{count}}",
      "archive.weeklySection": "Paquets hebdomadaires · {{count}}",
      "archive.emptyDaily": "Aucun journal enregistre pour l'instant.",
      "archive.emptyWeekly": "Aucun paquet hebdomadaire pour l'instant.",
      "side.emptyDaily": "Aucun journal enregistre pour l'instant",
      "side.emptyWeekly": "Aucun paquet hebdomadaire pour l'instant",
      "saved.diary": "Journal enregistre",
      "saved.records": "{{count}} entree(s)",
      "status.text.connected": "Codex pret",
      "status.text.connect": "Connecter Codex",
      "status.text.check": "Verifier Codex",
      "status.text.loading": "Verification de Codex",
      "status.action.connect": "Connecter",
      "status.action.check": "Verifier",
      "status.modelLabel": "Modele Codex",
      "status.detail.connected": "Tout est pret pour creer un journal.",
      "status.detail.login": "Une connexion est necessaire.",
      "status.detail.wait": "Merci de patienter un instant.",
      "connect.badge": "Codex",
      "connect.title": "Connectez Codex d'abord",
      "connect.body.connected":
        "Codex est pret. Choisissez simplement une date pour creer une entree tout de suite.",
      "connect.body.default": "Verifiez d'abord votre etat de connexion Codex.",
      "footer.ready":
        "Choisissez une date et creez un enregistrement pour lire le journal et le rapport directement dans l'application.",
      "footer.connectFirst": "Connectez d'abord Codex.",
      "footer.generating":
        "Lecture des resumes Chronicle et creation de l'entree du jour choisi en {{language}}...",
      "footer.cancelling": "Annulation de la generation en cours...",
      "footer.cancelled": "La generation a ete annulee.",
      "footer.generateFailed": "La generation a echoue.",
      "footer.connected":
        "Choisissez une date et creez un enregistrement pour lire le journal et le rapport directement dans l'application.",
      "footer.rechecked": "L'etat de connexion Codex a ete verifie a nouveau.",
      "footer.connectFailed": "La connexion a Codex a echoue.",
      "footer.noSavedForDate":
        "Aucun journal enregistre n'existe pour le {{date}}. Generer de nouveau remplacera l'entree de ce jour.",
      "footer.noSavedForDateCalendar":
        "Aucun journal enregistre n'existe pour le {{date}}. Si vous le creez, il sera enregistre en {{language}}.",
      "footer.openDiaryFailed": "Impossible d'ouvrir le journal du {{date}}.",
      "footer.openedDiary": "Journal du {{date}} ouvert.",
      "footer.openWeekFailed": "Impossible d'ouvrir la vue hebdomadaire.",
      "footer.openedWeek": "Vue hebdomadaire ouverte pour {{label}}.",
      "footer.calendarHint": "Choisissez une date dans l'onglet calendrier puis continuez depuis la.",
      "footer.generated": "Le journal du {{date}} a ete ouvert en {{language}}.{{saved}}",
      "toast.codexReady": "Codex est pret",
      "toast.sourceChanged": "Dossier source mis a jour",
      "toast.outputChanged": "Dossier de sortie mis a jour",
      "toast.nothingToCopy": "Rien a copier",
      "toast.copied": "Copie",
      "toast.copyFailed": "Echec de la copie",
      "toast.noSavedFile": "Aucun fichier enregistre.",
      "toast.openExternalFailed": "Impossible d'ouvrir le fichier enregistre.",
      "toast.cancelled": "Annule",
      "toast.todayAdjusted": "Deplacement vers la date effective d'aujourd'hui",
      "toast.languageChanged": "Langue changee en {{language}}",
      "toast.lengthChanged": "Longueur du journal changee en {{length}}",
      "toast.modelChanged": "Modele Codex change en {{model}}",
      "toast.todoCarried": "Ajoute au {{date}}.",
      "toast.todoAlreadyCarried": "Deja ajoute au {{date}}.",
      "toast.todoUpdated": "La tache a ete mise a jour.",
      "warning.webview": "Le pont WebView n'est pas pret.",
      "warning.timeout":
        "La reponse prend plus de {{seconds}} secondes. Les grosses journees peuvent demander 4 a 5 minutes, mais cette execution devra peut-etre etre relancee.",
      "length.short": "Court",
      "length.medium": "Moyen",
      "length.long": "Long",
      "length.very-long": "Tres long",
      "tag.today": "jour",
      "tag.decisions": "decisions",
      "tag.blockers": "blocages",
      "tag.tomorrow": "demain",
      "tag.diary": "journal",
      "mood.sparkle": "Etincelant",
      "mood.happy": "Heureux",
      "mood.soft": "Calme",
      "mood.tired": "Fatigue",
      "mood.blue": "Melancolique",
    },
    de: {
      "app.title": "Codex Diary",
      "quote.html": "Taegliche Notizen<br />formen das Morgen <span class=\"heart\">♡</span>",
      "date.label": "Bezugsdatum",
      "date.missing": "Datum waehlen",
      "action.prevDay": "Vortag",
      "action.nextDay": "Naechster Tag",
      "action.pickDate": "Datum waehlen",
      "action.more": "Mehr",
      "action.close": "Schliessen",
      "view.raw": "Markdown",
      "settings.panelAria": "Einstellungsbereich",
      "settings.eyebrow": "Einstellungen",
      "settings.summaryAria": "Einstellungsuebersicht",
      "settings.summaryStrong": "Passe den Tagebuchfluss an deinen Rhythmus an.",
      "settings.summaryCopy":
        "Lege Sprache, Tagesgrenze und Speichern einmal fest, damit der Ablauf jeden Tag gleich ruhig bleibt.",
      "settings.introBadge": "Standardsprache: {{language}}",
      "settings.outputSection": "Sprache und Ausgabe",
      "settings.languageHint": "Sowohl die Ausgabe als auch die App-Oberflaeche folgen dieser Sprache.",
      "settings.lengthLabel": "Tagebuchlaenge",
      "settings.lengthHint": "Waehle, ob das Tagebuch kurz, mittel oder sehr ausfuehrlich wirken soll.",
      "settings.boundaryHint": "Eintraege vor dieser Uhrzeit werden dem Vortag zugeordnet.",
      "settings.autoSaveTitle": "Nach der Erstellung automatisch speichern",
      "settings.autoSaveHint": "Speichert das Ergebnis sofort im Ausgabeordner.",
      "generate.finalize": "Tagebuch erstellen",
      "generate.draft": "Entwurf aktualisieren",
      "generate.todayFinalize": "Heutigen Eintrag erstellen",
      "generate.todayDraft": "Heutigen Entwurf aktualisieren",
      "generate.connect": "Nach Codex-Verbindung erstellen",
      "generate.connectTitle": "Verbinde zuerst Codex, bevor du generierst.",
      "generate.cancel": "Abbrechen",
      "generate.cancelling": "Wird abgebrochen...",
      "generate.cancelTitle": "Die aktuelle Erstellung abbrechen.",
      "generate.busy": "Wird erstellt...",
      "loading.detail.cancel": "Der aktuelle Entwurfslauf wird gestoppt.",
      "loading.detail.cancelled": "Die Erstellung wurde abgebrochen.",
      "loading.meta.slow":
        "Tage mit vielen Aufzeichnungen oder die Stufe Sehr lang koennen 4 bis 5 Minuten brauchen. Sobald es bereit ist, bekommst du eine Benachrichtigung.",
      "path.default": "Standardordner verwenden",
      "boundary.label": "{{hour}}:00",
      "boundary.chip": "{{hour}}:00 Grenze",
      "empty.report": "Es ist noch kein Bericht verfuegbar.",
      "empty.diary": "Es gibt noch kein Tagebuch zum Anzeigen.",
      "empty.titleWithDate": "Einen Eintrag fuer {{date}} erstellen?",
      "empty.titleToday": "Heute leise festhalten?",
      "empty.copyWithDate":
        "Fuer dieses Datum gibt es noch kein gespeichertes Tagebuch. Mit der Erstellen-Schaltflaeche wird es sofort in {{language}} erzeugt.",
      "empty.copyToday":
        "Mit der Erstellen-Schaltflaeche werden Chronicle-Zusammenfassungen direkt in Bericht und Tagebuch verwandelt.",
      "memo.placeholder": "Schreibe eine kurze Notiz auf, die du heute behalten moechtest.",
      "memo.saved": "Deine Notiz wurde gespeichert.",
      "foot.saved": "Automatisch gespeichert",
      "foot.preview": "Vorschau",
      "foot.modeFinalize": "Finales Tagebuch",
      "foot.modeDraft": "Entwurf aktualisiert",
      "foot.writtenAt": "Geschrieben um",
      "carryover.title": "In den heutigen Tag uebernommen",
      "carryover.subtitle": "{{count}} Aufgabe(n) warten hier",
      "carryover.from": "Von {{date}}",
      "todo.carryForward": "Auf morgen verschieben",
      "todo.carriedForward": "Bereits fuer morgen hinzugefuegt",
      "todo.markDone": "Als erledigt markieren",
      "todo.markOpen": "Als offen markieren",
      "timeline.more": "{{count}} weitere anzeigen",
      "timeline.all": "Alles ausklappen ({{count}})",
      "timeline.collapse": "Alles einklappen",
      "timeline.status": "{{visible}} angezeigt · {{remaining}} weitere uebrig",
      "calendar.savedCount": "{{count}} gespeichert",
      "calendar.weekRecords": "{{count}} Eintraege",
      "archive.copy": "Halte die Seitenleiste ruhig und nutze den Hauptbereich, um gespeicherte Tagebuecher in Ruhe zu durchsuchen.",
      "archive.recentSection": "Letzte Daten · {{count}}",
      "archive.weeklySection": "Wochenbündel · {{count}}",
      "archive.emptyDaily": "Noch keine gespeicherten Tagebuecher.",
      "archive.emptyWeekly": "Noch keine Wochenbuendel.",
      "side.emptyDaily": "Noch keine gespeicherten Tagebuecher",
      "side.emptyWeekly": "Noch keine Wochenbuendel",
      "saved.diary": "Gespeichertes Tagebuch",
      "saved.records": "{{count}} Eintraege",
      "status.text.connected": "Codex bereit",
      "status.text.connect": "Codex verbinden",
      "status.text.check": "Codex pruefen",
      "status.text.loading": "Codex wird geprueft",
      "status.action.connect": "Verbinden",
      "status.action.check": "Pruefen",
      "status.modelLabel": "Codex-Modell",
      "status.detail.connected": "Alles ist bereit, um ein Tagebuch zu erstellen.",
      "status.detail.login": "Eine Anmeldung ist erforderlich.",
      "status.detail.wait": "Bitte einen Moment warten.",
      "connect.badge": "Codex",
      "connect.title": "Zuerst Codex verbinden",
      "connect.body.connected": "Codex ist bereit. Waehle einfach ein Datum und erstelle sofort einen Eintrag.",
      "connect.body.default": "Pruefe zuerst deinen Codex-Anmeldestatus.",
      "footer.ready":
        "Waehle ein Datum und erstelle einen Eintrag, um Tagebuch und Bericht direkt in der App zu lesen.",
      "footer.connectFirst": "Verbinde zuerst Codex.",
      "footer.generating":
        "Chronicle-Zusammenfassungen werden gelesen und der ausgewaehlte Tag wird in {{language}} erstellt...",
      "footer.cancelling": "Die aktuelle Erstellung wird abgebrochen...",
      "footer.cancelled": "Die Erstellung wurde abgebrochen.",
      "footer.generateFailed": "Die Erstellung ist fehlgeschlagen.",
      "footer.connected":
        "Waehle ein Datum und erstelle einen Eintrag, um Tagebuch und Bericht direkt in der App zu lesen.",
      "footer.rechecked": "Der Codex-Status wurde erneut geprueft.",
      "footer.connectFailed": "Die Verbindung zu Codex ist fehlgeschlagen.",
      "footer.noSavedForDate":
        "Fuer {{date}} gibt es noch kein gespeichertes Tagebuch. Eine neue Generierung ueberschreibt den Eintrag dieses Tages.",
      "footer.noSavedForDateCalendar":
        "Fuer {{date}} gibt es noch kein gespeichertes Tagebuch. Beim Erstellen wird es in {{language}} gespeichert.",
      "footer.openDiaryFailed": "Das Tagebuch fuer {{date}} konnte nicht geoeffnet werden.",
      "footer.openedDiary": "Das Tagebuch fuer {{date}} wurde geoeffnet.",
      "footer.openWeekFailed": "Die Wochenansicht konnte nicht geoeffnet werden.",
      "footer.openedWeek": "Die Wochenansicht fuer {{label}} wurde geoeffnet.",
      "footer.calendarHint": "Waehle ein Datum im Kalender-Tab und mache dort weiter.",
      "footer.generated": "Das Tagebuch fuer {{date}} wurde in {{language}} geoeffnet.{{saved}}",
      "toast.codexReady": "Codex ist bereit",
      "toast.sourceChanged": "Quellordner aktualisiert",
      "toast.outputChanged": "Ausgabeordner aktualisiert",
      "toast.nothingToCopy": "Nichts zum Kopieren",
      "toast.copied": "Kopiert",
      "toast.copyFailed": "Kopieren fehlgeschlagen",
      "toast.noSavedFile": "Es gibt keine gespeicherte Datei.",
      "toast.openExternalFailed": "Die gespeicherte Datei konnte nicht geoeffnet werden.",
      "toast.cancelled": "Abgebrochen",
      "toast.todayAdjusted": "Zum heutigen Bezugsdatum gesprungen",
      "toast.languageChanged": "Sprache auf {{language}} gesetzt",
      "toast.lengthChanged": "Tagebuchlaenge auf {{length}} gesetzt",
      "toast.modelChanged": "Codex-Modell auf {{model}} gesetzt",
      "toast.todoCarried": "Zu {{date}} hinzugefuegt.",
      "toast.todoAlreadyCarried": "Bereits zu {{date}} hinzugefuegt.",
      "toast.todoUpdated": "Die Aufgabe wurde aktualisiert.",
      "warning.webview": "Die WebView-Bruecke ist noch nicht bereit.",
      "warning.timeout":
        "Die Antwort dauert laenger als {{seconds}} Sekunden. Umfangreiche Tage koennen 4 bis 5 Minuten brauchen, aber dieser Lauf muss eventuell neu gestartet werden.",
      "length.short": "Kurz",
      "length.medium": "Mittel",
      "length.long": "Lang",
      "length.very-long": "Sehr lang",
      "tag.today": "heute",
      "tag.decisions": "entscheidungen",
      "tag.blockers": "blocker",
      "tag.tomorrow": "morgen",
      "tag.diary": "tagebuch",
      "mood.sparkle": "Glanzvoll",
      "mood.happy": "Froh",
      "mood.soft": "Ruhig",
      "mood.tired": "Muede",
      "mood.blue": "Gedrueckt",
    },
    es: {
      "app.title": "Codex Diary",
      "quote.html": "Las notas del dia<br />dibujan el manana <span class=\"heart\">♡</span>",
      "date.label": "Fecha base",
      "date.missing": "Elige una fecha",
      "action.prevDay": "Dia anterior",
      "action.nextDay": "Dia siguiente",
      "action.pickDate": "Elegir fecha",
      "action.more": "Mas",
      "action.close": "Cerrar",
      "view.raw": "Markdown",
      "settings.panelAria": "Panel de ajustes",
      "settings.eyebrow": "Preferencias",
      "settings.summaryAria": "Resumen de ajustes",
      "settings.summaryStrong": "Ajusta el ritmo del diario a tu propia rutina.",
      "settings.summaryCopy":
        "Define una vez el idioma, el limite del dia y la forma de guardar para mantener un flujo estable cada dia.",
      "settings.introBadge": "Idioma predeterminado: {{language}}",
      "settings.outputSection": "Idioma y salida",
      "settings.languageHint": "Tanto el resultado del diario como la interfaz de la app siguen este idioma.",
      "settings.lengthLabel": "Longitud del diario",
      "settings.lengthHint": "Elige si el diario debe sentirse corto, medio o muy detallado.",
      "settings.boundaryHint": "Los registros anteriores a esta hora se agrupan en el dia anterior.",
      "settings.autoSaveTitle": "Guardar automaticamente despues de generar",
      "settings.autoSaveHint": "Guarda el resultado enseguida en la carpeta de salida.",
      "generate.finalize": "Crear diario",
      "generate.draft": "Actualizar borrador",
      "generate.todayFinalize": "Crear entrada de hoy",
      "generate.todayDraft": "Actualizar borrador de hoy",
      "generate.connect": "Crear despues de conectar Codex",
      "generate.connectTitle": "Conecta Codex antes de generar.",
      "generate.cancel": "Cancelar",
      "generate.cancelling": "Cancelando...",
      "generate.cancelTitle": "Cancelar la generacion actual.",
      "generate.busy": "Generando...",
      "loading.detail.cancel": "Deteniendo la generacion del borrador actual.",
      "loading.detail.cancelled": "La generacion se cancelo.",
      "loading.meta.slow":
        "Los dias con muchos registros o el modo Muy largo pueden tardar entre 4 y 5 minutos. Te avisaremos cuando este listo.",
      "path.default": "Usar la carpeta predeterminada",
      "boundary.label": "{{hour}}:00",
      "boundary.chip": "Limite {{hour}}:00",
      "empty.report": "Todavia no hay ningun informe disponible.",
      "empty.diary": "Todavia no hay ningun diario para mostrar.",
      "empty.titleWithDate": "Crear una entrada para {{date}}?",
      "empty.titleToday": "Quieres guardar hoy con calma?",
      "empty.copyWithDate":
        "Todavia no existe un diario guardado para esta fecha. Usa el boton de crear y se generara enseguida en {{language}}.",
      "empty.copyToday":
        "Usa el boton de crear y los resumenes de Chronicle se convertiran en informe y diario al mismo tiempo.",
      "memo.placeholder": "Escribe una nota corta que quieras guardar de hoy.",
      "memo.saved": "La nota se guardo.",
      "foot.saved": "Guardado automaticamente",
      "foot.preview": "Vista previa",
      "foot.modeFinalize": "Diario final",
      "foot.modeDraft": "Actualizacion de borrador",
      "foot.writtenAt": "Escrito a las",
      "carryover.title": "Traido a hoy",
      "carryover.subtitle": "{{count}} tarea(s) esperando aqui",
      "carryover.from": "Desde {{date}}",
      "todo.carryForward": "Agregar a manana",
      "todo.carriedForward": "Ya agregado a manana",
      "todo.markDone": "Marcar como hecho",
      "todo.markOpen": "Marcar como abierto",
      "timeline.more": "Mostrar {{count}} mas",
      "timeline.all": "Expandir todo ({{count}})",
      "timeline.collapse": "Contraer todo",
      "timeline.status": "Mostrando {{visible}} ahora · quedan {{remaining}}",
      "calendar.savedCount": "{{count}} guardados",
      "calendar.weekRecords": "{{count}} entradas",
      "archive.copy": "Deja la barra lateral ligera y usa el area principal para recorrer los diarios guardados con calma.",
      "archive.recentSection": "Fechas recientes · {{count}}",
      "archive.weeklySection": "Paquetes semanales · {{count}}",
      "archive.emptyDaily": "Todavia no hay diarios guardados.",
      "archive.emptyWeekly": "Todavia no hay paquetes semanales.",
      "side.emptyDaily": "Todavia no hay diarios guardados",
      "side.emptyWeekly": "Todavia no hay paquetes semanales",
      "saved.diary": "Diario guardado",
      "saved.records": "{{count}} entradas",
      "status.text.connected": "Codex listo",
      "status.text.connect": "Conectar Codex",
      "status.text.check": "Revisar Codex",
      "status.text.loading": "Revisando Codex",
      "status.action.connect": "Conectar",
      "status.action.check": "Revisar",
      "status.modelLabel": "Modelo de Codex",
      "status.detail.connected": "Todo esta listo para crear un diario.",
      "status.detail.login": "Hace falta iniciar sesion.",
      "status.detail.wait": "Espera un momento, por favor.",
      "connect.badge": "Codex",
      "connect.title": "Conecta primero Codex",
      "connect.body.connected": "Codex ya esta listo, asi que solo tienes que elegir una fecha y crear la entrada enseguida.",
      "connect.body.default": "Primero revisa tu estado de inicio de sesion en Codex.",
      "footer.ready":
        "Elige una fecha y crea un registro para leer el diario y el informe aqui mismo en la app.",
      "footer.connectFirst": "Conecta primero Codex.",
      "footer.generating":
        "Leyendo los resumenes de Chronicle y creando la entrada del dia elegido en {{language}}...",
      "footer.cancelling": "Cancelando la generacion actual...",
      "footer.cancelled": "La generacion se cancelo.",
      "footer.generateFailed": "La generacion fallo.",
      "footer.connected":
        "Elige una fecha y crea un registro para leer el diario y el informe aqui mismo en la app.",
      "footer.rechecked": "Se volvio a revisar el estado de conexion de Codex.",
      "footer.connectFailed": "No se pudo conectar con Codex.",
      "footer.noSavedForDate":
        "No hay ningun diario guardado para {{date}}. Si generas otra vez, se sobrescribira el registro de ese dia.",
      "footer.noSavedForDateCalendar":
        "No hay ningun diario guardado para {{date}}. Si lo generas, se guardara en {{language}}.",
      "footer.openDiaryFailed": "No se pudo abrir el diario de {{date}}.",
      "footer.openedDiary": "Se abrio el diario de {{date}}.",
      "footer.openWeekFailed": "No se pudo abrir la vista semanal.",
      "footer.openedWeek": "Se abrio la vista semanal de {{label}}.",
      "footer.calendarHint": "Elige una fecha en la pestana de calendario y sigue desde ahi.",
      "footer.generated": "Se abrio el diario de {{date}} en {{language}}.{{saved}}",
      "toast.codexReady": "Codex esta listo",
      "toast.sourceChanged": "Carpeta de origen actualizada",
      "toast.outputChanged": "Carpeta de salida actualizada",
      "toast.nothingToCopy": "No hay nada para copiar",
      "toast.copied": "Copiado",
      "toast.copyFailed": "Fallo al copiar",
      "toast.noSavedFile": "No hay ningun archivo guardado.",
      "toast.openExternalFailed": "No se pudo abrir el archivo guardado.",
      "toast.cancelled": "Cancelado",
      "toast.todayAdjusted": "Saltaste a la fecha efectiva de hoy",
      "toast.languageChanged": "Idioma cambiado a {{language}}",
      "toast.lengthChanged": "La longitud del diario cambio a {{length}}",
      "toast.modelChanged": "Modelo de Codex cambiado a {{model}}",
      "toast.todoCarried": "Agregado a {{date}}.",
      "toast.todoAlreadyCarried": "Ya estaba agregado a {{date}}.",
      "toast.todoUpdated": "La tarea se actualizo.",
      "warning.webview": "El puente de WebView todavia no esta listo.",
      "warning.timeout":
        "La respuesta esta tardando mas de {{seconds}} segundos. Los dias largos pueden tardar 4 o 5 minutos, pero puede que haya que reintentar esta ejecucion.",
      "length.short": "Corto",
      "length.medium": "Medio",
      "length.long": "Largo",
      "length.very-long": "Muy largo",
      "tag.today": "hoy",
      "tag.decisions": "decisiones",
      "tag.blockers": "bloqueos",
      "tag.tomorrow": "manana",
      "tag.diary": "diario",
      "mood.sparkle": "Brillante",
      "mood.happy": "Feliz",
      "mood.soft": "Calmo",
      "mood.tired": "Cansado",
      "mood.blue": "Decaido",
    },
    vi: {
      "app.title": "Codex Diary",
      "quote.html": "Ghi chep moi ngay<br />nuoi nen ngay mai <span class=\"heart\">♡</span>",
      "date.label": "Ngay goc",
      "date.missing": "Hay chon ngay",
      "action.prevDay": "Ngay truoc",
      "action.nextDay": "Ngay sau",
      "action.pickDate": "Chon ngay",
      "action.more": "Them",
      "action.close": "Dong",
      "view.raw": "Markdown",
      "settings.panelAria": "Bang cai dat",
      "settings.eyebrow": "Tuy chon",
      "settings.summaryAria": "Tom tat cai dat",
      "settings.summaryStrong": "Canh dong nhip ghi chep theo cach hop voi ban.",
      "settings.summaryCopy":
        "Dat ngon ngu, moc ngay va cach luu truoc de moi ngay deu co mot nhip tao nhat ky on dinh.",
      "settings.introBadge": "Ngon ngu mac dinh: {{language}}",
      "settings.outputSection": "Ngon ngu va dau ra",
      "settings.languageHint": "Ca ket qua nhat ky lan giao dien app deu di theo ngon ngu nay.",
      "settings.lengthLabel": "Do dai nhat ky",
      "settings.lengthHint": "Chon xem ban muon bai nhat ky ngan, vua hay rat day du.",
      "settings.boundaryHint": "Ban ghi truoc gio nay se duoc gom vao ngay hom truoc.",
      "settings.autoSaveTitle": "Tu dong luu sau khi tao",
      "settings.autoSaveHint": "Luu ket qua vao thu muc dau ra ngay sau khi tao xong.",
      "generate.finalize": "Tao nhat ky",
      "generate.draft": "Cap nhat ban nhap",
      "generate.todayFinalize": "Tao ban ghi hom nay",
      "generate.todayDraft": "Cap nhat ban nhap hom nay",
      "generate.connect": "Tao sau khi ket noi Codex",
      "generate.connectTitle": "Hay ket noi Codex truoc khi tao.",
      "generate.cancel": "Huy",
      "generate.cancelling": "Dang huy...",
      "generate.cancelTitle": "Huy lan tao dang dien ra.",
      "generate.busy": "Dang tao...",
      "loading.detail.cancel": "Dang dung lan tao ban nhap hien tai.",
      "loading.detail.cancelled": "Da huy qua trinh tao.",
      "loading.meta.slow":
        "Nhung ngay co nhieu ban ghi hoac che do Rat dai co the mat 4 den 5 phut. Khi xong app se bao cho ban.",
      "path.default": "Dung thu muc mac dinh",
      "boundary.label": "{{hour}}:00",
      "boundary.chip": "Moc {{hour}}:00",
      "empty.report": "Chua co bao cao nao de hien thi.",
      "empty.diary": "Chua co nhat ky nao de hien thi.",
      "empty.titleWithDate": "Tao mot ban ghi cho {{date}}?",
      "empty.titleToday": "Muon nhe nhang giu lai hom nay khong?",
      "empty.copyWithDate":
        "Ngay nay chua co nhat ky da luu. Bam nut tao va ket qua se duoc tao ngay bang {{language}}.",
      "empty.copyToday":
        "Bam nut tao de bien tong ket Chronicle thanh ca bao cao lan nhat ky ngay trong app.",
      "memo.placeholder": "Ghi mot ghi chu ngan ma ban muon giu lai tu hom nay.",
      "memo.saved": "Da luu ghi chu cua ban.",
      "foot.saved": "Da tu dong luu",
      "foot.preview": "Xem truoc",
      "foot.modeFinalize": "Nhat ky cuoi",
      "foot.modeDraft": "Cap nhat ban nhap",
      "foot.writtenAt": "Viet luc",
      "carryover.title": "Mang sang hom nay",
      "carryover.subtitle": "{{count}} viec dang cho o day",
      "carryover.from": "Tu {{date}}",
      "todo.carryForward": "Them vao ngay mai",
      "todo.carriedForward": "Da them vao ngay mai",
      "todo.markDone": "Danh dau da xong",
      "todo.markOpen": "Danh dau chua xong",
      "timeline.more": "Hien them {{count}} muc",
      "timeline.all": "Mo rong tat ca ({{count}})",
      "timeline.collapse": "Thu gon tat ca",
      "timeline.status": "Dang hien {{visible}} muc · con {{remaining}} muc nua",
      "calendar.savedCount": "Da luu {{count}} muc",
      "calendar.weekRecords": "{{count}} ban ghi",
      "archive.copy": "Giu thanh ben gon gang va xem lai nhung nhat ky da luu trong khu vuc chinh.",
      "archive.recentSection": "Ngay gan day · {{count}}",
      "archive.weeklySection": "Cum theo tuan · {{count}}",
      "archive.emptyDaily": "Chua co nhat ky da luu.",
      "archive.emptyWeekly": "Chua co cum theo tuan.",
      "side.emptyDaily": "Chua co nhat ky da luu",
      "side.emptyWeekly": "Chua co cum theo tuan",
      "saved.diary": "Nhat ky da luu",
      "saved.records": "{{count}} ban ghi",
      "status.text.connected": "Codex san sang",
      "status.text.connect": "Ket noi Codex",
      "status.text.check": "Kiem tra Codex",
      "status.text.loading": "Dang kiem tra Codex",
      "status.action.connect": "Ket noi",
      "status.action.check": "Kiem tra",
      "status.modelLabel": "Mo hinh Codex",
      "status.detail.connected": "Da san sang de tao nhat ky ngay bay gio.",
      "status.detail.login": "Can dang nhap truoc.",
      "status.detail.wait": "Hay doi mot chut nhe.",
      "connect.badge": "Codex",
      "connect.title": "Hay ket noi Codex truoc",
      "connect.body.connected":
        "Codex da san sang, chi can chon ngay la co the tao ban ghi ngay lap tuc.",
      "connect.body.default": "Hay kiem tra trang thai dang nhap Codex truoc.",
      "footer.ready":
        "Chon ngay va tao ban ghi de doc nhat ky va bao cao ngay trong ung dung.",
      "footer.connectFirst": "Hay ket noi Codex truoc.",
      "footer.generating":
        "Dang doc cac tong ket Chronicle va tao ban ghi cua ngay da chon bang {{language}}...",
      "footer.cancelling": "Dang huy qua trinh tao hien tai...",
      "footer.cancelled": "Da huy qua trinh tao.",
      "footer.generateFailed": "Tao that bai.",
      "footer.connected":
        "Chon ngay va tao ban ghi de doc nhat ky va bao cao ngay trong ung dung.",
      "footer.rechecked": "Da kiem tra lai trang thai ket noi Codex.",
      "footer.connectFailed": "Ket noi Codex that bai.",
      "footer.noSavedForDate":
        "Ngay {{date}} chua co nhat ky da luu. Neu tao lai, ban ghi cua ngay nay se bi ghi de.",
      "footer.noSavedForDateCalendar":
        "Ngay {{date}} chua co nhat ky da luu. Neu tao, ket qua se duoc luu bang {{language}}.",
      "footer.openDiaryFailed": "Khong mo duoc nhat ky cua {{date}}.",
      "footer.openedDiary": "Da mo nhat ky cua {{date}}.",
      "footer.openWeekFailed": "Khong mo duoc che do xem theo tuan.",
      "footer.openedWeek": "Da mo che do xem tuan cua {{label}}.",
      "footer.calendarHint": "Hay chon ngay trong tab lich roi tiep tuc tu do.",
      "footer.generated": "Da mo nhat ky cua {{date}} bang {{language}}.{{saved}}",
      "toast.codexReady": "Codex da san sang",
      "toast.sourceChanged": "Da cap nhat thu muc nguon",
      "toast.outputChanged": "Da cap nhat thu muc dau ra",
      "toast.nothingToCopy": "Khong co gi de sao chep",
      "toast.copied": "Da sao chep",
      "toast.copyFailed": "Sao chep that bai",
      "toast.noSavedFile": "Khong co tep da luu.",
      "toast.openExternalFailed": "Khong mo duoc tep da luu.",
      "toast.cancelled": "Da huy",
      "toast.todayAdjusted": "Da nhay den ngay hieu luc cua hom nay",
      "toast.languageChanged": "Da doi ngon ngu sang {{language}}",
      "toast.lengthChanged": "Da doi do dai nhat ky sang {{length}}",
      "toast.modelChanged": "Da doi mo hinh Codex sang {{model}}",
      "toast.todoCarried": "Da them vao {{date}}.",
      "toast.todoAlreadyCarried": "Da co trong {{date}} roi.",
      "toast.todoUpdated": "Da cap nhat cong viec.",
      "warning.webview": "Cau noi WebView chua san sang.",
      "warning.timeout":
        "Phan hoi dang lau hon {{seconds}} giay. Nhung ngay dai co the mat 4 den 5 phut, nhung lan chay nay co the can thu lai.",
      "length.short": "Ngan",
      "length.medium": "Vua",
      "length.long": "Dai",
      "length.very-long": "Rat dai",
      "tag.today": "homnay",
      "tag.decisions": "quyetdinh",
      "tag.blockers": "vuongmac",
      "tag.tomorrow": "ngaymai",
      "tag.diary": "nhatky",
      "mood.sparkle": "Rang ro",
      "mood.happy": "Vui",
      "mood.soft": "Em",
      "mood.tired": "Met",
      "mood.blue": "Tram",
    },
    th: {
      "app.title": "Codex Diary",
      "quote.html": "บันทึกทุกวัน<br />ค่อยๆ สร้างวันพรุ่งนี้ <span class=\"heart\">♡</span>",
      "date.label": "วันที่อ้างอิง",
      "date.missing": "เลือกวันที่ก่อน",
      "action.prevDay": "วันก่อนหน้า",
      "action.nextDay": "วันถัดไป",
      "action.pickDate": "เลือกวันที่",
      "action.more": "เพิ่มเติม",
      "action.close": "ปิด",
      "view.raw": "Markdown",
      "settings.panelAria": "แผงตั้งค่า",
      "settings.eyebrow": "การตั้งค่า",
      "settings.summaryAria": "สรุปการตั้งค่า",
      "settings.summaryStrong": "ปรับจังหวะการเขียนบันทึกให้เข้ากับวันของคุณได้",
      "settings.summaryCopy": "ตั้งค่าภาษา เส้นแบ่งวัน และการบันทึกล่วงหน้าไว้ก่อน เพื่อให้เขียนไดอารีได้ด้วยจังหวะที่คงที่ทุกวัน",
      "settings.introBadge": "ภาษาเริ่มต้น: {{language}}",
      "settings.outputSection": "ภาษาและผลลัพธ์",
      "settings.languageHint": "ทั้งผลลัพธ์ที่สร้างและ UI ของแอปจะใช้ภาษานี้ไปพร้อมกัน",
      "settings.lengthLabel": "ความยาวของไดอารี",
      "settings.lengthHint": "เลือกได้ว่าต้องการให้ไดอารีสั้น ปานกลาง หรือยาวมากแค่ไหน",
      "settings.boundaryHint": "บันทึกก่อนเวลานี้จะถูกรวมไว้ในไดอารีของวันก่อนหน้า",
      "settings.autoSaveTitle": "บันทึกอัตโนมัติหลังสร้างเสร็จ",
      "settings.autoSaveHint": "บันทึกผลลัพธ์ลงโฟลเดอร์ปลายทางทันทีหลังสร้างเสร็จ",
      "generate.finalize": "สร้างไดอารี",
      "generate.draft": "อัปเดตร่าง",
      "generate.todayFinalize": "สร้างบันทึกของวันนี้",
      "generate.todayDraft": "อัปเดตร่างของวันนี้",
      "generate.connect": "สร้างหลังเชื่อมต่อ Codex",
      "generate.connectTitle": "เชื่อมต่อ Codex ก่อนจึงจะสร้างได้",
      "generate.cancel": "ยกเลิก",
      "generate.cancelling": "กำลังยกเลิก...",
      "generate.cancelTitle": "ยกเลิกการสร้างที่กำลังทำอยู่",
      "generate.busy": "กำลังสร้าง...",
      "loading.detail.cancel": "กำลังหยุดการสร้างร่างครั้งนี้",
      "loading.detail.cancelled": "ยกเลิกการสร้างแล้ว",
      "loading.meta.slow": "วันที่มีบันทึกเยอะหรือโหมด ยาวมาก อาจใช้เวลา 4 ถึง 5 นาที พอพร้อมแล้วเราจะแจ้งให้รู้",
      "path.default": "ใช้โฟลเดอร์เริ่มต้น",
      "boundary.label": "{{hour}}:00",
      "boundary.chip": "เกณฑ์ {{hour}}:00",
      "empty.report": "ยังไม่มีรายงานให้แสดง",
      "empty.diary": "ยังไม่มีไดอารีให้แสดง",
      "empty.titleWithDate": "จะสร้างบันทึกของ {{date}} ไหม?",
      "empty.titleToday": "อยากเก็บวันนี้ไว้อย่างนุ่มนวลไหม?",
      "empty.copyWithDate": "วันนี้ยังไม่มีไดอารีที่บันทึกไว้ กดปุ่มสร้างแล้วผลลัพธ์จะถูกสร้างเป็น {{language}} ทันที",
      "empty.copyToday": "กดปุ่มสร้างแล้วสรุป Chronicle จะถูกแปลงเป็นทั้งรายงานและไดอารีในครั้งเดียว",
      "memo.placeholder": "เขียนโน้ตสั้นๆ ที่อยากเก็บไว้จากวันนี้",
      "memo.saved": "บันทึกโน้ตแล้ว",
      "foot.saved": "บันทึกอัตโนมัติแล้ว",
      "foot.preview": "ตัวอย่าง",
      "foot.modeFinalize": "ไดอารีฉบับสมบูรณ์",
      "foot.modeDraft": "อัปเดตร่าง",
      "foot.writtenAt": "เขียนเมื่อ",
      "carryover.title": "สิ่งที่พามาถึงวันนี้",
      "carryover.subtitle": "มีงาน {{count}} รายการรออยู่ที่นี่",
      "carryover.from": "จาก {{date}}",
      "todo.carryForward": "เพิ่มไปพรุ่งนี้",
      "todo.carriedForward": "เพิ่มไปพรุ่งนี้แล้ว",
      "todo.markDone": "ทำเครื่องหมายว่าเสร็จ",
      "todo.markOpen": "ทำเครื่องหมายว่ายังค้าง",
      "timeline.more": "แสดงเพิ่มอีก {{count}} รายการ",
      "timeline.all": "ขยายทั้งหมด ({{count}})",
      "timeline.collapse": "ยุบทั้งหมด",
      "timeline.status": "กำลังแสดง {{visible}} รายการ · เหลืออีก {{remaining}}",
      "calendar.savedCount": "บันทึกแล้ว {{count}} รายการ",
      "calendar.weekRecords": "{{count}} รายการ",
      "archive.copy": "ให้แถบด้านข้างโล่งไว้ แล้วใช้พื้นที่หลักในการไล่อ่านไดอารีที่บันทึกไว้",
      "archive.recentSection": "วันที่ล่าสุด · {{count}}",
      "archive.weeklySection": "ชุดรายสัปดาห์ · {{count}}",
      "archive.emptyDaily": "ยังไม่มีไดอารีที่บันทึกไว้",
      "archive.emptyWeekly": "ยังไม่มีชุดรายสัปดาห์",
      "side.emptyDaily": "ยังไม่มีไดอารีที่บันทึกไว้",
      "side.emptyWeekly": "ยังไม่มีชุดรายสัปดาห์",
      "saved.diary": "ไดอารีที่บันทึกไว้",
      "saved.records": "{{count}} รายการ",
      "status.text.connected": "Codex พร้อมแล้ว",
      "status.text.connect": "เชื่อมต่อ Codex",
      "status.text.check": "ตรวจสอบ Codex",
      "status.text.loading": "กำลังตรวจสอบ Codex",
      "status.action.connect": "เชื่อมต่อ",
      "status.action.check": "ตรวจสอบ",
      "status.modelLabel": "โมเดล Codex",
      "status.detail.connected": "พร้อมสร้างไดอารีได้ทันที",
      "status.detail.login": "ต้องเข้าสู่ระบบก่อน",
      "status.detail.wait": "กรุณารอสักครู่",
      "connect.badge": "Codex",
      "connect.title": "เชื่อมต่อ Codex ก่อน",
      "connect.body.connected": "Codex พร้อมแล้ว แค่เลือกวันที่ก็สร้างบันทึกได้ทันที",
      "connect.body.default": "ตรวจสอบสถานะการล็อกอิน Codex ก่อน",
      "footer.ready": "เลือกวันที่แล้วสร้างบันทึก จากนั้นจะอ่านไดอารีและรายงานได้ตรงนี้ในแอปเลย",
      "footer.connectFirst": "เชื่อมต่อ Codex ก่อน",
      "footer.generating": "กำลังอ่านสรุป Chronicle และสร้างบันทึกของวันที่เลือกเป็นภาษา {{language}}...",
      "footer.cancelling": "กำลังยกเลิกการสร้างปัจจุบัน...",
      "footer.cancelled": "ยกเลิกการสร้างแล้ว",
      "footer.generateFailed": "สร้างไม่สำเร็จ",
      "footer.connected": "เลือกวันที่แล้วสร้างบันทึก จากนั้นจะอ่านไดอารีและรายงานได้ตรงนี้ในแอปเลย",
      "footer.rechecked": "ตรวจสอบสถานะการเชื่อมต่อ Codex อีกครั้งแล้ว",
      "footer.connectFailed": "เชื่อมต่อ Codex ไม่สำเร็จ",
      "footer.noSavedForDate": "ยังไม่มีไดอารีที่บันทึกไว้สำหรับ {{date}} หากสร้างใหม่อีกครั้ง ระบบจะเขียนทับบันทึกของวันนั้น",
      "footer.noSavedForDateCalendar": "ยังไม่มีไดอารีที่บันทึกไว้สำหรับ {{date}} หากสร้าง ผลลัพธ์จะถูกบันทึกเป็นภาษา {{language}}",
      "footer.openDiaryFailed": "เปิดไดอารีของ {{date}} ไม่สำเร็จ",
      "footer.openedDiary": "เปิดไดอารีของ {{date}} แล้ว",
      "footer.openWeekFailed": "เปิดมุมมองรายสัปดาห์ไม่สำเร็จ",
      "footer.openedWeek": "เปิดมุมมองรายสัปดาห์ของ {{label}} แล้ว",
      "footer.calendarHint": "เลือกวันที่ในแท็บปฏิทินแล้วค่อยทำต่อจากตรงนั้น",
      "footer.generated": "เปิดไดอารีของ {{date}} เป็นภาษา {{language}} แล้ว{{saved}}",
      "toast.codexReady": "Codex พร้อมแล้ว",
      "toast.sourceChanged": "อัปเดตโฟลเดอร์ต้นทางแล้ว",
      "toast.outputChanged": "อัปเดตโฟลเดอร์ปลายทางแล้ว",
      "toast.nothingToCopy": "ไม่มีอะไรให้คัดลอก",
      "toast.copied": "คัดลอกแล้ว",
      "toast.copyFailed": "คัดลอกไม่สำเร็จ",
      "toast.noSavedFile": "ไม่มีไฟล์ที่บันทึกไว้",
      "toast.openExternalFailed": "เปิดไฟล์ที่บันทึกไว้ไม่สำเร็จ",
      "toast.cancelled": "ยกเลิกแล้ว",
      "toast.todayAdjusted": "ย้ายไปยังวันที่มีผลของวันนี้แล้ว",
      "toast.languageChanged": "เปลี่ยนภาษาเป็น {{language}} แล้ว",
      "toast.lengthChanged": "เปลี่ยนความยาวไดอารีเป็น {{length}} แล้ว",
      "toast.modelChanged": "เปลี่ยนโมเดล Codex เป็น {{model}} แล้ว",
      "toast.todoCarried": "เพิ่มไปยัง {{date}} แล้ว",
      "toast.todoAlreadyCarried": "มีอยู่ใน {{date}} แล้ว",
      "toast.todoUpdated": "อัปเดตงานแล้ว",
      "warning.webview": "สะพาน WebView ยังไม่พร้อม",
      "warning.timeout": "การตอบกลับใช้เวลานานกว่า {{seconds}} วินาที วันที่ยาวอาจใช้ 4 ถึง 5 นาที แต่รอบนี้อาจต้องลองใหม่",
      "length.short": "สั้น",
      "length.medium": "ปานกลาง",
      "length.long": "ยาว",
      "length.very-long": "ยาวมาก",
      "tag.today": "วันนี้",
      "tag.decisions": "การตัดสินใจ",
      "tag.blockers": "จุดที่ติด",
      "tag.tomorrow": "พรุ่งนี้",
      "tag.diary": "ไดอารี",
      "mood.sparkle": "สดใส",
      "mood.happy": "มีความสุข",
      "mood.soft": "สงบ",
      "mood.tired": "เหนื่อย",
      "mood.blue": "หม่นๆ",
    },
    ru: {
      "app.title": "Codex Diary",
      "quote.html": "Ежедневные заметки<br />тихо формируют завтра <span class=\"heart\">♡</span>",
      "date.label": "Базовая дата",
      "date.missing": "Выберите дату",
      "action.prevDay": "Предыдущий день",
      "action.nextDay": "Следующий день",
      "action.pickDate": "Выбрать дату",
      "action.more": "Еще",
      "action.close": "Закрыть",
      "view.raw": "Markdown",
      "settings.panelAria": "Панель настроек",
      "settings.eyebrow": "Параметры",
      "settings.summaryAria": "Сводка настроек",
      "settings.summaryStrong": "Подстройте ритм дневника под свой рабочий день.",
      "settings.summaryCopy":
        "Заранее задайте язык, границу дня и способ сохранения, чтобы каждый день вести дневник в одном и том же ритме.",
      "settings.introBadge": "Язык по умолчанию: {{language}}",
      "settings.outputSection": "Язык и вывод",
      "settings.languageHint": "И итоговый дневник, и интерфейс приложения следуют этому языку.",
      "settings.lengthLabel": "Длина дневника",
      "settings.lengthHint": "Выберите, насколько коротким или подробным должен быть дневник.",
      "settings.boundaryHint": "Записи до этого времени относятся к предыдущему дню.",
      "settings.autoSaveTitle": "Автоматически сохранять после генерации",
      "settings.autoSaveHint": "Сразу сохранять результат в папку вывода.",
      "generate.finalize": "Создать дневник",
      "generate.draft": "Обновить черновик",
      "generate.todayFinalize": "Создать запись за сегодня",
      "generate.todayDraft": "Обновить черновик за сегодня",
      "generate.connect": "Создать после подключения Codex",
      "generate.connectTitle": "Сначала подключите Codex.",
      "generate.cancel": "Отмена",
      "generate.cancelling": "Отмена...",
      "generate.cancelTitle": "Отменить текущую генерацию.",
      "generate.busy": "Создание...",
      "loading.detail.cancel": "Останавливаю текущий запуск черновика.",
      "loading.detail.cancelled": "Генерация была отменена.",
      "loading.meta.slow":
        "Дни с большим количеством записей или режим Очень длинно могут занять 4–5 минут. Когда все будет готово, приложение сообщит об этом.",
      "path.default": "Использовать папку по умолчанию",
      "boundary.label": "{{hour}}:00",
      "boundary.chip": "Граница {{hour}}:00",
      "empty.report": "Пока нет отчета для показа.",
      "empty.diary": "Пока нет дневника для показа.",
      "empty.titleWithDate": "Создать запись за {{date}}?",
      "empty.titleToday": "Мягко сохранить сегодняшний день?",
      "empty.copyWithDate":
        "Для этой даты еще нет сохраненного дневника. Нажмите кнопку создания, и запись сразу появится на {{language}}.",
      "empty.copyToday":
        "Нажмите кнопку создания, и сводки Chronicle превратятся сразу и в отчет, и в дневник.",
      "memo.placeholder": "Напишите короткую заметку, которую хотите сохранить с этого дня.",
      "memo.saved": "Заметка сохранена.",
      "foot.saved": "Автосохранено",
      "foot.preview": "Предпросмотр",
      "foot.modeFinalize": "Финальный дневник",
      "foot.modeDraft": "Обновление черновика",
      "foot.writtenAt": "Написано в",
      "carryover.title": "Перенесено в сегодня",
      "carryover.subtitle": "Здесь ждут {{count}} задач(и)",
      "carryover.from": "Из {{date}}",
      "todo.carryForward": "Добавить на завтра",
      "todo.carriedForward": "Уже добавлено на завтра",
      "todo.markDone": "Отметить выполненным",
      "todo.markOpen": "Вернуть в открытые",
      "timeline.more": "Показать еще {{count}}",
      "timeline.all": "Развернуть все ({{count}})",
      "timeline.collapse": "Свернуть все",
      "timeline.status": "Сейчас показано {{visible}} · осталось {{remaining}}",
      "calendar.savedCount": "Сохранено {{count}}",
      "calendar.weekRecords": "{{count}} записей",
      "archive.copy": "Пусть боковая панель остается легкой, а сохраненные дневники спокойно просматриваются в основной области.",
      "archive.recentSection": "Последние даты · {{count}}",
      "archive.weeklySection": "Недельные подборки · {{count}}",
      "archive.emptyDaily": "Пока нет сохраненных дневников.",
      "archive.emptyWeekly": "Пока нет недельных подборок.",
      "side.emptyDaily": "Пока нет сохраненных дневников",
      "side.emptyWeekly": "Пока нет недельных подборок",
      "saved.diary": "Сохраненный дневник",
      "saved.records": "{{count}} записей",
      "status.text.connected": "Codex готов",
      "status.text.connect": "Подключить Codex",
      "status.text.check": "Проверить Codex",
      "status.text.loading": "Проверка Codex",
      "status.action.connect": "Подключить",
      "status.action.check": "Проверить",
      "status.modelLabel": "Модель Codex",
      "status.detail.connected": "Все готово для создания дневника.",
      "status.detail.login": "Нужно войти в систему.",
      "status.detail.wait": "Подождите немного.",
      "connect.badge": "Codex",
      "connect.title": "Сначала подключите Codex",
      "connect.body.connected": "Codex уже готов, поэтому достаточно выбрать дату и сразу создать запись.",
      "connect.body.default": "Сначала проверьте, вошли ли вы в Codex.",
      "footer.ready":
        "Выберите дату и создайте запись, чтобы сразу читать дневник и отчет прямо в приложении.",
      "footer.connectFirst": "Сначала подключите Codex.",
      "footer.generating":
        "Читаю сводки Chronicle и создаю запись выбранного дня на {{language}}...",
      "footer.cancelling": "Отменяю текущую генерацию...",
      "footer.cancelled": "Генерация отменена.",
      "footer.generateFailed": "Не удалось завершить генерацию.",
      "footer.connected":
        "Выберите дату и создайте запись, чтобы сразу читать дневник и отчет прямо в приложении.",
      "footer.rechecked": "Статус подключения Codex проверен еще раз.",
      "footer.connectFailed": "Не удалось подключиться к Codex.",
      "footer.noSavedForDate":
        "Для {{date}} еще нет сохраненного дневника. Повторная генерация перезапишет запись этого дня.",
      "footer.noSavedForDateCalendar":
        "Для {{date}} еще нет сохраненного дневника. Если создать его сейчас, он сохранится на {{language}}.",
      "footer.openDiaryFailed": "Не удалось открыть дневник за {{date}}.",
      "footer.openedDiary": "Открыт дневник за {{date}}.",
      "footer.openWeekFailed": "Не удалось открыть недельный вид.",
      "footer.openedWeek": "Открыт недельный вид для {{label}}.",
      "footer.calendarHint": "Выберите дату на вкладке календаря и продолжайте оттуда.",
      "footer.generated": "Дневник за {{date}} открыт на {{language}}.{{saved}}",
      "toast.codexReady": "Codex готов",
      "toast.sourceChanged": "Папка источника обновлена",
      "toast.outputChanged": "Папка вывода обновлена",
      "toast.nothingToCopy": "Нечего копировать",
      "toast.copied": "Скопировано",
      "toast.copyFailed": "Не удалось скопировать",
      "toast.noSavedFile": "Нет сохраненного файла.",
      "toast.openExternalFailed": "Не удалось открыть сохраненный файл.",
      "toast.cancelled": "Отменено",
      "toast.todayAdjusted": "Переход к актуальной дате на сегодня",
      "toast.languageChanged": "Язык изменен на {{language}}",
      "toast.lengthChanged": "Длина дневника изменена на {{length}}",
      "toast.modelChanged": "Модель Codex изменена на {{model}}",
      "toast.todoCarried": "Добавлено к {{date}}.",
      "toast.todoAlreadyCarried": "Уже добавлено к {{date}}.",
      "toast.todoUpdated": "Задача обновлена.",
      "warning.webview": "Мост WebView еще не готов.",
      "warning.timeout":
        "Ответ идет дольше {{seconds}} секунд. Насыщенные дни могут занимать 4–5 минут, но этот запуск, возможно, придется повторить.",
      "length.short": "Коротко",
      "length.medium": "Средне",
      "length.long": "Длинно",
      "length.very-long": "Очень длинно",
      "tag.today": "сегодня",
      "tag.decisions": "решения",
      "tag.blockers": "блокеры",
      "tag.tomorrow": "завтра",
      "tag.diary": "дневник",
      "mood.sparkle": "Искристо",
      "mood.happy": "Радостно",
      "mood.soft": "Спокойно",
      "mood.tired": "Усталость",
      "mood.blue": "Грустно",
    },
    hi: {
      "app.title": "Codex Diary",
      "quote.html": "रोज़ की नोट्स<br />कल को धीरे से गढ़ती हैं <span class=\"heart\">♡</span>",
      "date.label": "आधार तिथि",
      "date.missing": "तारीख चुनिए",
      "action.prevDay": "पिछला दिन",
      "action.nextDay": "अगला दिन",
      "action.pickDate": "तारीख चुनें",
      "action.more": "और",
      "action.close": "बंद करें",
      "view.raw": "Markdown",
      "settings.panelAria": "सेटिंग्स पैनल",
      "settings.eyebrow": "पसंद",
      "settings.summaryAria": "सेटिंग्स सारांश",
      "settings.summaryStrong": "डायरी का रिदम अपने काम के बहाव के मुताबिक सेट करें।",
      "settings.summaryCopy":
        "भाषा, दिन की सीमा और सेव करने का तरीका पहले तय कर लें, ताकि हर दिन एक ही शांत लय में डायरी बन सके।",
      "settings.introBadge": "डिफ़ॉल्ट भाषा: {{language}}",
      "settings.outputSection": "भाषा और आउटपुट",
      "settings.languageHint": "डायरी आउटपुट और ऐप UI दोनों इसी भाषा का पालन करेंगे।",
      "settings.lengthLabel": "डायरी की लंबाई",
      "settings.lengthHint": "चुनें कि डायरी छोटी, मध्यम या बहुत विस्तार वाली लगे।",
      "settings.boundaryHint": "इस समय से पहले के रिकॉर्ड पिछले दिन में जोड़े जाएंगे।",
      "settings.autoSaveTitle": "बनने के बाद अपने आप सेव करें",
      "settings.autoSaveHint": "रिज़ल्ट को तुरंत आउटपुट फ़ोल्डर में सेव करें।",
      "generate.finalize": "डायरी बनाएं",
      "generate.draft": "ड्राफ्ट अपडेट करें",
      "generate.todayFinalize": "आज की एंट्री बनाएं",
      "generate.todayDraft": "आज का ड्राफ्ट अपडेट करें",
      "generate.connect": "Codex कनेक्ट होने के बाद बनाएं",
      "generate.connectTitle": "बनाने से पहले Codex कनेक्ट करें।",
      "generate.cancel": "रद्द करें",
      "generate.cancelling": "रद्द किया जा रहा है...",
      "generate.cancelTitle": "मौजूदा जनरेशन को रद्द करें।",
      "generate.busy": "बन रहा है...",
      "loading.detail.cancel": "अभी चल रहे ड्राफ्ट रन को रोका जा रहा है।",
      "loading.detail.cancelled": "जनरेशन रद्द कर दी गई।",
      "loading.meta.slow":
        "जिन दिनों में रिकॉर्ड बहुत हों या Very long चुना हो, उनमें 4 से 5 मिनट लग सकते हैं। तैयार होने पर ऐप आपको बता देगा।",
      "path.default": "डिफ़ॉल्ट फ़ोल्डर इस्तेमाल करें",
      "boundary.label": "{{hour}}:00",
      "boundary.chip": "{{hour}}:00 सीमा",
      "empty.report": "अभी कोई रिपोर्ट उपलब्ध नहीं है।",
      "empty.diary": "अभी दिखाने के लिए कोई डायरी नहीं है।",
      "empty.titleWithDate": "{{date}} के लिए एंट्री बनाएं?",
      "empty.titleToday": "क्या आज को हल्के से संजोना है?",
      "empty.copyWithDate": "इस तारीख के लिए अभी कोई सेव की गई डायरी नहीं है। Create दबाते ही यह {{language}} में बन जाएगी।",
      "empty.copyToday": "Create दबाएं, Chronicle सारांशों से रिपोर्ट और डायरी दोनों एक साथ बन जाएंगे।",
      "memo.placeholder": "आज की कोई छोटी बात लिखें जिसे आप संभाल कर रखना चाहते हैं।",
      "memo.saved": "आपकी नोट सेव हो गई।",
      "foot.saved": "ऑटो-सेव हो गया",
      "foot.preview": "प्रीव्यू",
      "foot.modeFinalize": "अंतिम डायरी",
      "foot.modeDraft": "ड्राफ्ट अपडेट",
      "foot.writtenAt": "लिखा गया",
      "carryover.title": "आज में लाई गई चीज़ें",
      "carryover.subtitle": "{{count}} काम यहां आपका इंतज़ार कर रहे हैं",
      "carryover.from": "{{date}} से",
      "todo.carryForward": "कल में जोड़ें",
      "todo.carriedForward": "पहले ही कल में जोड़ा जा चुका है",
      "todo.markDone": "पूरा हुआ चिह्नित करें",
      "todo.markOpen": "खुला चिह्नित करें",
      "timeline.more": "{{count}} और दिखाएं",
      "timeline.all": "सब खोलें ({{count}})",
      "timeline.collapse": "सब समेटें",
      "timeline.status": "अभी {{visible}} दिख रहे हैं · {{remaining}} बाकी हैं",
      "calendar.savedCount": "{{count}} सेव",
      "calendar.weekRecords": "{{count}} एंट्री",
      "archive.copy": "साइडबार को हल्का रखें और सेव की गई डायरी को मुख्य हिस्से में आराम से देखें।",
      "archive.recentSection": "हाल की तारीखें · {{count}}",
      "archive.weeklySection": "साप्ताहिक बंडल · {{count}}",
      "archive.emptyDaily": "अभी कोई सेव की गई डायरी नहीं है।",
      "archive.emptyWeekly": "अभी कोई साप्ताहिक बंडल नहीं है।",
      "side.emptyDaily": "अभी कोई सेव की गई डायरी नहीं है",
      "side.emptyWeekly": "अभी कोई साप्ताहिक बंडल नहीं है",
      "saved.diary": "सेव की गई डायरी",
      "saved.records": "{{count}} एंट्री",
      "status.text.connected": "Codex तैयार",
      "status.text.connect": "Codex कनेक्ट करें",
      "status.text.check": "Codex जांचें",
      "status.text.loading": "Codex जांचा जा रहा है",
      "status.action.connect": "कनेक्ट करें",
      "status.action.check": "जांचें",
      "status.modelLabel": "Codex मॉडल",
      "status.detail.connected": "अब डायरी बनाने के लिए सब तैयार है।",
      "status.detail.login": "पहले लॉग इन करना होगा।",
      "status.detail.wait": "कृपया थोड़ी देर रुकिए।",
      "connect.badge": "Codex",
      "connect.title": "पहले Codex कनेक्ट करें",
      "connect.body.connected": "Codex तैयार है, इसलिए बस तारीख चुनते ही एंट्री बनाई जा सकती है।",
      "connect.body.default": "पहले अपना Codex लॉगिन स्टेटस जांच लें।",
      "footer.ready":
        "तारीख चुनकर रिकॉर्ड बनाएं, फिर डायरी और रिपोर्ट यहीं ऐप के अंदर पढ़ी जा सकेगी।",
      "footer.connectFirst": "पहले Codex कनेक्ट करें।",
      "footer.generating":
        "Chronicle सारांश पढ़े जा रहे हैं और चुने गए दिन की एंट्री {{language}} में बनाई जा रही है...",
      "footer.cancelling": "मौजूदा जनरेशन रद्द की जा रही है...",
      "footer.cancelled": "जनरेशन रद्द कर दी गई।",
      "footer.generateFailed": "जनरेशन पूरी नहीं हो पाई।",
      "footer.connected":
        "तारीख चुनकर रिकॉर्ड बनाएं, फिर डायरी और रिपोर्ट यहीं ऐप के अंदर पढ़ी जा सकेगी।",
      "footer.rechecked": "Codex कनेक्शन स्टेटस फिर से जांच लिया गया।",
      "footer.connectFailed": "Codex से कनेक्ट नहीं हो पाया।",
      "footer.noSavedForDate":
        "{{date}} के लिए अभी कोई सेव की गई डायरी नहीं है। फिर से जनरेट करने पर उस दिन की एंट्री ओवरराइट हो जाएगी।",
      "footer.noSavedForDateCalendar":
        "{{date}} के लिए अभी कोई सेव की गई डायरी नहीं है। अगर अभी बनाते हैं, तो यह {{language}} में सेव होगी।",
      "footer.openDiaryFailed": "{{date}} की डायरी खोली नहीं जा सकी।",
      "footer.openedDiary": "{{date}} की डायरी खोल दी गई।",
      "footer.openWeekFailed": "साप्ताहिक दृश्य नहीं खोला जा सका।",
      "footer.openedWeek": "{{label}} का साप्ताहिक दृश्य खोल दिया गया।",
      "footer.calendarHint": "कैलेंडर टैब में तारीख चुनें और वहीं से आगे बढ़ें।",
      "footer.generated": "{{date}} की डायरी {{language}} में खोल दी गई।{{saved}}",
      "toast.codexReady": "Codex तैयार है",
      "toast.sourceChanged": "सोर्स फ़ोल्डर अपडेट हो गया",
      "toast.outputChanged": "आउटपुट फ़ोल्डर अपडेट हो गया",
      "toast.nothingToCopy": "कॉपी करने के लिए कुछ नहीं है",
      "toast.copied": "कॉपी हो गया",
      "toast.copyFailed": "कॉपी नहीं हो पाई",
      "toast.noSavedFile": "कोई सेव की गई फ़ाइल नहीं है।",
      "toast.openExternalFailed": "सेव की गई फ़ाइल खोली नहीं जा सकी।",
      "toast.cancelled": "रद्द किया गया",
      "toast.todayAdjusted": "आज की प्रभावी तारीख पर आ गए",
      "toast.languageChanged": "भाषा {{language}} कर दी गई",
      "toast.lengthChanged": "डायरी की लंबाई {{length}} कर दी गई",
      "toast.modelChanged": "Codex मॉडल {{model}} कर दिया गया",
      "toast.todoCarried": "{{date}} में जोड़ दिया गया।",
      "toast.todoAlreadyCarried": "{{date}} में पहले से जोड़ा जा चुका है।",
      "toast.todoUpdated": "काम अपडेट कर दिया गया।",
      "warning.webview": "WebView ब्रिज अभी तैयार नहीं है।",
      "warning.timeout":
        "रिस्पॉन्स को {{seconds}} सेकंड से ज़्यादा समय लग रहा है। लंबे दिन 4 से 5 मिनट ले सकते हैं, लेकिन इस रन को शायद दोबारा आज़माना पड़े।",
      "length.short": "छोटा",
      "length.medium": "मध्यम",
      "length.long": "लंबा",
      "length.very-long": "बहुत लंबा",
      "tag.today": "आज",
      "tag.decisions": "फैसले",
      "tag.blockers": "रुकावटें",
      "tag.tomorrow": "कल",
      "tag.diary": "डायरी",
      "mood.sparkle": "चमकता",
      "mood.happy": "खुश",
      "mood.soft": "शांत",
      "mood.tired": "थका",
      "mood.blue": "उदास",
    },
  };

  for (const [lang, entries] of Object.entries(complements)) {
    copy[lang] = {
      ...entries,
      ...(copy[lang] || {}),
    };
  }

  const refinements = {
    fr: {
      "quote.html": "Les notes du jour<br />dessinent le lendemain <span class=\"heart\">♡</span>",
      "settings.summaryStrong": "Ajustez le rythme du journal à votre façon.",
      "settings.summaryCopy":
        "Définissez la langue, la limite du jour et le mode d’enregistrement une bonne fois pour garder un rituel stable.",
      "settings.lengthHint": "Choisissez si le journal doit rester bref, équilibré ou vraiment détaillé.",
      "settings.boundaryHint": "Tout ce qui se passe avant cette heure est rangé dans la journée précédente.",
      "generate.connectTitle": "Connectez Codex avant de lancer la génération.",
      "loading.meta.slow":
        "Les journées très denses ou le mode Très long peuvent prendre 4 à 5 minutes. L’app vous préviendra dès que ce sera prêt.",
      "empty.titleToday": "Envie de garder une trace douce d’aujourd’hui ?",
      "empty.copyToday":
        "Utilisez le bouton de création et les résumés Chronicle seront transformés en rapport et en journal dans le même élan.",
      "footer.ready":
        "Choisissez une date puis créez un enregistrement pour lire le journal et le rapport directement dans l’application.",
      "footer.generating":
        "Lecture des résumés Chronicle et création de l’entrée du jour choisi en {{language}}...",
      "footer.generated": "Le journal du {{date}} est ouvert en {{language}}.{{saved}}",
      "toast.copied": "Copié",
      "warning.timeout":
        "La réponse prend plus de {{seconds}} secondes. Les journées chargées peuvent demander 4 à 5 minutes, mais ce lancement devra peut-être être relancé.",
      "mood.sparkle": "Rayonnant",
      "mood.soft": "Paisible",
    },
    de: {
      "quote.html": "Tägliche Notizen<br />tragen leise ins Morgen <span class=\"heart\">♡</span>",
      "settings.summaryStrong": "Passe den Tagebuchfluss an deinen eigenen Rhythmus an.",
      "settings.summaryCopy":
        "Lege Sprache, Tagesgrenze und Speichern einmal fest, damit sich das Tagebuch jeden Tag gleich ruhig anfühlt.",
      "settings.lengthHint": "Wähle, ob das Tagebuch kurz, ausgewogen oder besonders ausführlich sein soll.",
      "settings.boundaryHint": "Einträge vor dieser Uhrzeit wandern in den Vortag.",
      "generate.connectTitle": "Verbinde zuerst Codex, bevor du die Generierung startest.",
      "loading.meta.slow":
        "Tage mit vielen Aufzeichnungen oder die Stufe Sehr lang können 4 bis 5 Minuten brauchen. Sobald alles bereit ist, bekommst du eine Mitteilung.",
      "empty.titleToday": "Möchtest du den heutigen Tag leise festhalten?",
      "empty.copyToday":
        "Mit der Erstellen-Schaltfläche werden Chronicle-Zusammenfassungen direkt zu Bericht und Tagebuch geformt.",
      "footer.ready":
        "Wähle ein Datum und erstelle einen Eintrag, damit du Tagebuch und Bericht direkt in der App lesen kannst.",
      "footer.generating":
        "Chronicle-Zusammenfassungen werden gelesen und der gewählte Tag wird in {{language}} ausgearbeitet...",
      "footer.generated": "Das Tagebuch für {{date}} wurde in {{language}} geöffnet.{{saved}}",
      "toast.todayAdjusted": "Zum wirksamen Tagesdatum von heute gesprungen",
      "warning.timeout":
        "Die Antwort dauert länger als {{seconds}} Sekunden. Umfangreiche Tage können 4 bis 5 Minuten brauchen, aber dieser Lauf muss eventuell neu gestartet werden.",
      "mood.sparkle": "Leicht",
      "mood.blue": "Gedämpft",
    },
    es: {
      "quote.html": "Las notas del día<br />dibujan poco a poco el mañana <span class=\"heart\">♡</span>",
      "settings.summaryStrong": "Ajusta el ritmo del diario para que se parezca más a tu rutina.",
      "settings.summaryCopy":
        "Deja fijados el idioma, el corte del día y la forma de guardar para que escribir el diario tenga siempre el mismo pulso.",
      "settings.lengthHint": "Elige si quieres un diario breve, equilibrado o bastante más amplio.",
      "settings.boundaryHint": "Los registros anteriores a esta hora se agrupan dentro del día anterior.",
      "generate.connectTitle": "Conecta Codex antes de empezar la generación.",
      "loading.meta.slow":
        "Los días con muchos registros o el modo Muy largo pueden tardar entre 4 y 5 minutos. La app te avisará cuando esté listo.",
      "empty.titleToday": "¿Quieres guardar hoy con un tono más suave?",
      "empty.copyToday":
        "Usa el botón de crear y los resúmenes de Chronicle se convertirán a la vez en informe y diario.",
      "footer.ready":
        "Elige una fecha y crea un registro para leer el diario y el informe aquí mismo, dentro de la app.",
      "footer.generating":
        "Leyendo los resúmenes de Chronicle y preparando la entrada del día elegido en {{language}}...",
      "footer.generated": "Se abrió el diario de {{date}} en {{language}}.{{saved}}",
      "toast.todayAdjusted": "Saltaste a la fecha efectiva de hoy",
      "warning.timeout":
        "La respuesta está tardando más de {{seconds}} segundos. Los días largos pueden llevar 4 o 5 minutos, pero esta ejecución quizá deba repetirse.",
      "mood.sparkle": "Luminoso",
      "mood.blue": "Apagado",
    },
    vi: {
      "quote.html": "Nhung ghi chep moi ngay<br />nhe nhang nuoi lon ngay mai <span class=\"heart\">♡</span>",
      "settings.summaryStrong": "Canh nhip viet nhat ky sao cho hop voi dong viec cua ban.",
      "settings.summaryCopy":
        "Dat san ngon ngu, moc ngay va cach luu de moi ngay deu co mot nhip ghi chep deu dan, de tho.",
      "settings.lengthHint": "Chon xem ban muon bai nhat ky ngan gon, vua phai hay that day dan.",
      "settings.boundaryHint": "Nhung ban ghi truoc moc gio nay se duoc tinh vao ngay hom truoc.",
      "generate.connectTitle": "Hay ket noi Codex truoc khi bat dau tao.",
      "loading.meta.slow":
        "Nhung ngay co rat nhieu ban ghi hoac che do Rat dai co the mat 4 den 5 phut. Khi xong app se bao cho ban ngay.",
      "empty.titleToday": "Muon giu lai hom nay theo mot cach nhe nhang khong?",
      "empty.copyToday":
        "Bam nut tao de bien tong ket Chronicle thanh ca bao cao lan nhat ky trong cung mot luot.",
      "footer.ready":
        "Chon ngay va tao ban ghi de doc nhat ky va bao cao ngay trong app, khong can mo ra ngoai.",
      "footer.generating":
        "Dang doc cac tong ket Chronicle va chuan bi ban ghi cua ngay da chon bang {{language}}...",
      "footer.generated": "Da mo nhat ky cua {{date}} bang {{language}}.{{saved}}",
      "toast.todayAdjusted": "Da nhay den ngay hieu luc cua hom nay",
      "warning.timeout":
        "Phan hoi dang lau hon {{seconds}} giay. Nhung ngay dai co the mat 4 den 5 phut, nhung lan chay nay co the can thu lai.",
      "mood.sparkle": "Rang rang",
      "mood.soft": "Diu",
    },
  };

  for (const [lang, entries] of Object.entries(refinements)) {
    copy[lang] = {
      ...(copy[lang] || {}),
      ...entries,
    };
  }

  const readinessLabels = {
    en: {
      "readiness.title": "Before creating",
      "readiness.prereqTitle": "Chronicle summaries are required",
      "readiness.prereqBody":
        "Codex Diary does not read recordings or screenshots directly. Turn on Chronicle first, then use the folder where Chronicle writes Markdown summaries.",
      "readiness.sourceCount": "{{count}} Markdown files",
      "readiness.sourceMissing": "No Chronicle summary folder found",
      "readiness.sourceEmpty": "No Chronicle Markdown summaries found",
      "readiness.outputReady": "Ready",
      "readiness.outputMissing": "Created automatically when saving",
    },
    ko: {
      "readiness.title": "생성 전 확인",
      "readiness.prereqTitle": "Chronicle 요약이 필요해요",
      "readiness.prereqBody":
        "Codex Diary는 화면 녹화나 스크린샷을 직접 읽지 않아요. 먼저 Chronicle을 켜서 Markdown 요약을 만들고, 그 요약 폴더를 입력 폴더로 사용해 주세요.",
      "readiness.sourceCount": "Markdown {{count}}개",
      "readiness.sourceMissing": "Chronicle 요약 폴더를 찾지 못했어요",
      "readiness.sourceEmpty": "Chronicle Markdown 요약이 아직 없어요",
      "readiness.outputReady": "준비됨",
      "readiness.outputMissing": "저장할 때 자동으로 만들어요",
    },
    ja: {
      "readiness.title": "作成前の確認",
      "readiness.prereqTitle": "Chronicle の要約が必要です",
      "readiness.prereqBody":
        "Codex Diary は録画やスクリーンショットを直接読みません。先に Chronicle を有効にし、Markdown 要約が保存されるフォルダーを入力にしてください。",
      "readiness.sourceCount": "Markdown {{count}} 件",
      "readiness.sourceMissing": "Chronicle 要約フォルダーが見つかりません",
      "readiness.sourceEmpty": "Chronicle Markdown 要約がまだありません",
      "readiness.outputReady": "準備完了",
      "readiness.outputMissing": "保存時に自動作成",
    },
    zh: {
      "readiness.title": "创建前检查",
      "readiness.prereqTitle": "需要 Chronicle 摘要",
      "readiness.prereqBody":
        "Codex Diary 不会直接读取录屏或截图。请先开启 Chronicle，然后选择它写入 Markdown 摘要的文件夹。",
      "readiness.sourceCount": "{{count}} 个 Markdown",
      "readiness.sourceMissing": "未找到 Chronicle 摘要文件夹",
      "readiness.sourceEmpty": "还没有 Chronicle Markdown 摘要",
      "readiness.outputReady": "已就绪",
      "readiness.outputMissing": "保存时自动创建",
    },
    fr: {
      "readiness.title": "Avant la creation",
      "readiness.prereqTitle": "Les resumes Chronicle sont requis",
      "readiness.prereqBody":
        "Codex Diary ne lit pas directement les enregistrements ni les captures d'ecran. Activez d'abord Chronicle, puis utilisez le dossier ou il ecrit les resumes Markdown.",
      "readiness.sourceCount": "{{count}} fichiers Markdown",
      "readiness.sourceMissing": "Dossier de resumes Chronicle introuvable",
      "readiness.sourceEmpty": "Aucun resume Markdown Chronicle pour l'instant",
      "readiness.outputReady": "Pret",
      "readiness.outputMissing": "Cree automatiquement a l'enregistrement",
    },
    de: {
      "readiness.title": "Vor dem Erstellen",
      "readiness.prereqTitle": "Chronicle-Zusammenfassungen sind erforderlich",
      "readiness.prereqBody":
        "Codex Diary liest keine Aufnahmen oder Screenshots direkt. Aktiviere zuerst Chronicle und nutze dann den Ordner, in den Chronicle Markdown-Zusammenfassungen schreibt.",
      "readiness.sourceCount": "{{count}} Markdown-Dateien",
      "readiness.sourceMissing": "Chronicle-Zusammenfassungsordner nicht gefunden",
      "readiness.sourceEmpty": "Noch keine Chronicle-Markdown-Zusammenfassungen",
      "readiness.outputReady": "Bereit",
      "readiness.outputMissing": "Wird beim Speichern erstellt",
    },
    es: {
      "readiness.title": "Antes de crear",
      "readiness.prereqTitle": "Se necesitan resumenes de Chronicle",
      "readiness.prereqBody":
        "Codex Diary no lee grabaciones ni capturas directamente. Activa Chronicle primero y usa la carpeta donde escribe sus resumenes Markdown.",
      "readiness.sourceCount": "{{count}} archivos Markdown",
      "readiness.sourceMissing": "No se encontro la carpeta de resumenes de Chronicle",
      "readiness.sourceEmpty": "Aun no hay resumenes Markdown de Chronicle",
      "readiness.outputReady": "Listo",
      "readiness.outputMissing": "Se crea automaticamente al guardar",
    },
    vi: {
      "readiness.title": "Truoc khi tao",
      "readiness.prereqTitle": "Can tom tat Chronicle",
      "readiness.prereqBody":
        "Codex Diary khong doc truc tiep ban ghi man hinh hay anh chup. Hay bat Chronicle truoc, roi dung thu muc noi Chronicle ghi tom tat Markdown.",
      "readiness.sourceCount": "{{count}} tep Markdown",
      "readiness.sourceMissing": "Khong tim thay thu muc tom tat Chronicle",
      "readiness.sourceEmpty": "Chua co tom tat Markdown Chronicle",
      "readiness.outputReady": "San sang",
      "readiness.outputMissing": "Tu tao khi luu",
    },
    th: {
      "readiness.title": "ก่อนสร้าง",
      "readiness.prereqTitle": "ต้องมีสรุปจาก Chronicle",
      "readiness.prereqBody":
        "Codex Diary ไม่อ่านไฟล์อัดหน้าจอหรือภาพหน้าจอโดยตรง กรุณาเปิด Chronicle ก่อน แล้วเลือกโฟลเดอร์ที่ Chronicle เขียนสรุป Markdown ไว้",
      "readiness.sourceCount": "Markdown {{count}} ไฟล์",
      "readiness.sourceMissing": "ไม่พบโฟลเดอร์สรุป Chronicle",
      "readiness.sourceEmpty": "ยังไม่มีสรุป Chronicle แบบ Markdown",
      "readiness.outputReady": "พร้อม",
      "readiness.outputMissing": "สร้างอัตโนมัติเมื่อบันทึก",
    },
    ru: {
      "readiness.title": "Перед созданием",
      "readiness.prereqTitle": "Нужны сводки Chronicle",
      "readiness.prereqBody":
        "Codex Diary не читает записи экрана или скриншоты напрямую. Сначала включите Chronicle, затем выберите папку, куда Chronicle пишет Markdown-сводки.",
      "readiness.sourceCount": "{{count}} файлов Markdown",
      "readiness.sourceMissing": "Папка сводок Chronicle не найдена",
      "readiness.sourceEmpty": "Пока нет Markdown-сводок Chronicle",
      "readiness.outputReady": "Готово",
      "readiness.outputMissing": "Будет создано при сохранении",
    },
    hi: {
      "readiness.title": "बनाने से पहले",
      "readiness.prereqTitle": "Chronicle सारांश जरूरी हैं",
      "readiness.prereqBody":
        "Codex Diary रिकॉर्डिंग या स्क्रीनशॉट सीधे नहीं पढ़ता। पहले Chronicle चालू करें, फिर वह फ़ोल्डर चुनें जहां Chronicle Markdown सारांश लिखता है।",
      "readiness.sourceCount": "{{count}} Markdown फाइलें",
      "readiness.sourceMissing": "Chronicle सारांश फ़ोल्डर नहीं मिला",
      "readiness.sourceEmpty": "अभी Chronicle Markdown सारांश नहीं हैं",
      "readiness.outputReady": "तैयार",
      "readiness.outputMissing": "सेव करते समय अपने आप बनेगा",
    },
  };

  for (const lang of Object.keys(copy)) {
    copy[lang] = {
      ...(copy[lang] || {}),
      ...(readinessLabels[lang] || readinessLabels.en),
    };
  }
})();
