window.CODEX_DIARY_UI_COPY = {
  en: {
    "app.title": "Codex Diary",
    "brand.sub": "Turn Chronicle summaries into a diary",
    "nav.diary": "Diary",
    "nav.calendar": "Calendar",
    "nav.archive": "Archive",
    "side.recent": "Recent dates",
    "side.weekly": "Weekly collections",
    "quote.html": "Daily notes<br />shape tomorrow <span class=\"heart\">♡</span>",
    "settings.title": "Settings",
    "date.label": "Base date",
    "date.missing": "Choose a date",
    "action.prevDay": "Previous day",
    "action.nextDay": "Next day",
    "action.pickDate": "Choose date",
    "action.today": "Today",
    "action.more": "More",
    "action.change": "Change",
    "action.close": "Close",
    "view.diary": "Diary",
    "view.report": "Report",
    "view.raw": "Markdown",
    "menu.viewWeek": "View this week",
    "menu.copy": "Copy current view",
    "menu.external": "Open in external app",
    "settings.panelAria": "Settings panel",
    "settings.eyebrow": "Preferences",
    "settings.summaryAria": "Settings summary",
    "settings.summaryStrong": "Tune the diary flow to your rhythm.",
    "settings.summaryCopy":
      "Set the language, day boundary, and save behavior once to keep a steady routine.",
    "settings.introBadge": "Default language: {{language}}",
    "settings.outputSection": "Language & Output",
    "settings.languageLabel": "Language",
    "settings.languageHint": "Both the diary output and the app UI follow this language.",
    "settings.boundaryLabel": "Day boundary",
    "settings.boundaryHint": "Records before this time are grouped into the previous day.",
    "settings.modeLabel": "Generation mode",
    "settings.modeFinalize": "Finalize diary",
    "settings.modeDraft": "Update draft",
    "settings.autoSaveTitle": "Save automatically after generation",
    "settings.autoSaveHint": "Save the result to the output folder right away.",
    "settings.pathsSection": "Paths",
    "settings.sourceLabel": "Source folder",
    "settings.outputLabel": "Output folder",
    "generate.finalize": "Create diary",
    "generate.draft": "Update draft",
    "generate.todayFinalize": "Create today's entry",
    "generate.todayDraft": "Update today's draft",
    "generate.connect": "Create after connecting Codex",
    "generate.connectTitle": "Connect Codex before generating.",
    "generate.busy": "Generating...",
    "path.default": "Use default folder",
    "boundary.label": "{{hour}}:00",
    "boundary.chip": "{{hour}}:00 boundary",
    "empty.report": "No report is available yet.",
    "empty.diary": "There is no diary to display yet.",
    "empty.titleWithDate": "Create an entry for {{date}}?",
    "empty.titleToday": "Want to quietly capture today?",
    "empty.copyWithDate":
      "No saved diary exists for this date yet. Use the create button to generate it immediately in {{language}}.",
    "empty.copyToday":
      "Use the create button and Chronicle summaries will be shaped into both a report and a diary.",
    "diary.title": "Today's diary",
    "mood.label": "Today's mood",
    "summary.label": "One-line summary",
    "memo.placeholder": "Write a short note you want to keep from today.",
    "memo.save": "Save",
    "memo.saved": "Saved your memo.",
    "foot.saved": "Auto-saved",
    "foot.preview": "Preview",
    "foot.modeFinalize": "Final diary",
    "foot.modeDraft": "Draft update",
    "foot.writtenAt": "Written at",
    "report.today": "What I did today",
    "report.highlights": "Highlights",
    "report.blockers": "Blockers",
    "report.tomorrow": "Tomorrow",
    "report.reflection": "Short reflection",
    "timeline.title": "Timeline flow",
    "timeline.more": "Show {{count}} more",
    "timeline.all": "Expand all ({{count}})",
    "timeline.collapse": "Collapse all",
    "timeline.status": "Showing {{visible}} now · {{remaining}} more left",
    "calendar.savedCount": "{{count}} saved",
    "calendar.weekSection": "Weekly collections",
    "calendar.weekRecords": "{{count}} entries",
    "archive.eyebrow": "Archive",
    "archive.title": "Browse daily notes and weekly bundles in one place",
    "archive.copy": "Keep the sidebar light and use the main area to browse saved diaries.",
    "archive.recentSection": "Recent dates · {{count}}",
    "archive.weeklySection": "Weekly bundles · {{count}}",
    "archive.emptyDaily": "No saved diaries yet.",
    "archive.emptyWeekly": "No weekly bundles yet.",
    "side.emptyDaily": "No saved diaries yet",
    "side.emptyWeekly": "No weekly bundles yet",
    "saved.diary": "Saved diary",
    "saved.records": "{{count}} entries",
    "status.text.connected": "Codex Ready",
    "status.text.connect": "Connect Codex",
    "status.text.check": "Check Codex",
    "status.text.loading": "Checking Codex",
    "status.action.connect": "Connect",
    "status.action.check": "Check",
    "status.detail.connected": "Ready to create a diary.",
    "status.detail.login": "Login is required.",
    "status.detail.wait": "Please wait a moment.",
    "connect.badge": "Codex",
    "connect.title": "Connect Codex first",
    "connect.body.connected":
      "Codex is ready, so you can pick a date and generate an entry right away.",
    "connect.body.default": "Check your Codex login status first.",
    "footer.ready":
      "Pick a date and generate a record to read the diary and report right here in the app.",
    "footer.connectFirst": "Connect Codex first.",
    "footer.generating":
      "Reading Chronicle summaries and creating the selected day's entry in {{language}}...",
    "footer.generateFailed": "Generation failed.",
    "footer.connected":
      "Pick a date and generate a record to read the diary and report right here in the app.",
    "footer.rechecked": "Checked the Codex connection status again.",
    "footer.connectFailed": "Failed to connect Codex.",
    "footer.noSavedForDate":
      "No saved diary exists for {{date}}. Generating again will overwrite that day's record.",
    "footer.noSavedForDateCalendar":
      "No saved diary exists for {{date}}. Generate it and it will be saved in {{language}}.",
    "footer.openDiaryFailed": "Couldn't open the diary for {{date}}.",
    "footer.openedDiary": "Opened the diary for {{date}}.",
    "footer.openWeekFailed": "Couldn't open the weekly view.",
    "footer.openedWeek": "Opened the weekly view for {{label}}.",
    "footer.calendarHint": "Pick a date in the calendar tab and continue from there.",
    "footer.generated":
      "Opened the diary for {{date}} in {{language}}.{{saved}}",
    "toast.codexReady": "Codex is ready",
    "toast.sourceChanged": "Source folder updated",
    "toast.outputChanged": "Output folder updated",
    "toast.nothingToCopy": "Nothing to copy",
    "toast.copied": "Copied",
    "toast.copyFailed": "Copy failed",
    "toast.noSavedFile": "There is no saved file.",
    "toast.todayAdjusted": "Jumped to today's effective date",
    "toast.languageChanged": "Language changed to {{language}}",
    "warning.webview": "The WebView bridge is not ready.",
    "warning.timeout":
      "The response did not arrive within {{seconds}} seconds. Check whether the Chronicle folder is correct.",
    "mood.sparkle": "Sparkly",
    "mood.happy": "Happy",
    "mood.soft": "Calm",
    "mood.tired": "Tired",
    "mood.blue": "Blue",
  },
  ko: {
    "app.title": "Codex Diary",
    "brand.sub": "Chronicle 요약을 일기로",
    "nav.diary": "일기",
    "nav.calendar": "캘린더",
    "nav.archive": "보관함",
    "side.recent": "최근 날짜",
    "side.weekly": "주간 모아보기",
    "quote.html": "매일의 기록이<br />내일의 나를 만든다 <span class=\"heart\">♡</span>",
    "settings.title": "설정",
    "date.label": "기준 날짜",
    "date.missing": "날짜를 골라 주세요",
    "action.prevDay": "전날",
    "action.nextDay": "다음날",
    "action.pickDate": "날짜 선택",
    "action.today": "오늘로",
    "action.more": "더 보기",
    "action.change": "변경",
    "action.close": "닫기",
    "view.diary": "일기",
    "view.report": "보고서",
    "view.raw": "Markdown",
    "menu.viewWeek": "해당 주 보기",
    "menu.copy": "현재 보기 복사",
    "menu.external": "외부 앱으로 열기",
    "settings.panelAria": "설정 패널",
    "settings.eyebrow": "Preferences",
    "settings.summaryAria": "설정 요약",
    "settings.summaryStrong": "기록 흐름을 차분하게 맞춰 둘 수 있어요.",
    "settings.summaryCopy":
      "출력 언어, 하루 경계 시각, 저장 방식을 먼저 정해 두면 매일 같은 리듬으로 일기를 만들 수 있어요.",
    "settings.introBadge": "기본 언어: {{language}}",
    "settings.outputSection": "출력",
    "settings.languageLabel": "언어",
    "settings.languageHint": "생성 결과와 앱 UI가 이 언어를 함께 따라가요.",
    "settings.boundaryLabel": "하루 경계 시각",
    "settings.boundaryHint": "이 시각 이전 기록은 전날 일기에 포함돼요.",
    "settings.modeLabel": "생성 모드",
    "settings.modeFinalize": "최종 일기",
    "settings.modeDraft": "초안 갱신",
    "settings.autoSaveTitle": "생성 후 자동으로 저장하기",
    "settings.autoSaveHint": "생성 직후 결과를 출력 폴더에 바로 저장해요.",
    "settings.pathsSection": "경로",
    "settings.sourceLabel": "입력 폴더",
    "settings.outputLabel": "출력 폴더",
    "generate.finalize": "일기 생성",
    "generate.draft": "초안 갱신",
    "generate.todayFinalize": "오늘 기록 생성",
    "generate.todayDraft": "오늘 초안 갱신",
    "generate.connect": "Codex 연결 후 생성",
    "generate.connectTitle": "먼저 Codex를 연결해야 생성할 수 있어요.",
    "generate.busy": "생성 중...",
    "path.default": "기본 폴더 사용",
    "boundary.label": "{{hour}}시",
    "boundary.chip": "{{hour}}시 기준",
    "empty.report": "아직 보고서 내용이 없어요.",
    "empty.diary": "표시할 일기가 아직 없어요.",
    "empty.titleWithDate": "{{date}} 기록을 만들어 볼까요?",
    "empty.titleToday": "오늘을 조용히 기록해 볼까요?",
    "empty.copyWithDate":
      "이 날짜는 아직 저장된 일기가 없어요. 생성 버튼을 누르면 {{language}} 결과로 바로 생성돼요.",
    "empty.copyToday": "생성 버튼을 누르면 Chronicle 요약이 보고서와 일기로 다정하게 정리돼요.",
    "diary.title": "오늘의 일기",
    "mood.label": "오늘의 기분",
    "summary.label": "오늘의 한 줄 요약",
    "memo.placeholder": "오늘 떠오른 짧은 메모를 적어 두세요.",
    "memo.save": "저장하기",
    "memo.saved": "메모를 저장했어요",
    "foot.saved": "자동 저장됨",
    "foot.preview": "미리보기",
    "foot.modeFinalize": "최종 일기",
    "foot.modeDraft": "초안 갱신",
    "foot.writtenAt": "작성 시간",
    "report.today": "오늘 한 일",
    "report.highlights": "오늘의 하이라이트",
    "report.blockers": "막혔던 점",
    "report.tomorrow": "내일 할 일",
    "report.reflection": "짧은 회고",
    "timeline.title": "시간순 흐름",
    "timeline.more": "{{count}}개 더 보기",
    "timeline.all": "전체 펼치기 ({{count}})",
    "timeline.collapse": "전체 접기",
    "timeline.status": "지금 {{visible}}개를 보고 있어요 · {{remaining}}개가 더 남아 있어요",
    "calendar.savedCount": "저장 {{count}}개",
    "calendar.weekSection": "주간 모음",
    "calendar.weekRecords": "{{count}}개 기록",
    "archive.eyebrow": "보관함",
    "archive.title": "날짜별 기록과 주간 묶음을 한곳에서",
    "archive.copy": "사이드바는 가볍게 두고, 저장된 일기 탐색은 넓은 메인 화면에서 보도록 정리했어요.",
    "archive.recentSection": "최근 날짜 · {{count}}개",
    "archive.weeklySection": "주간 묶음 · {{count}}개",
    "archive.emptyDaily": "아직 저장된 일기가 없어요.",
    "archive.emptyWeekly": "주간 묶음이 아직 없어요.",
    "side.emptyDaily": "아직 저장된 일기가 없어요",
    "side.emptyWeekly": "주간 묶음은 아직 없어요",
    "saved.diary": "저장된 일기",
    "saved.records": "{{count}}개 기록",
    "status.text.connected": "Codex Ready",
    "status.text.connect": "Connect Codex",
    "status.text.check": "Codex Check",
    "status.text.loading": "Checking Codex",
    "status.action.connect": "연결",
    "status.action.check": "확인",
    "status.detail.connected": "일기 생성 준비가 끝났어요.",
    "status.detail.login": "로그인이 필요해요.",
    "status.detail.wait": "잠시만 기다려 주세요.",
    "connect.badge": "Codex",
    "connect.title": "먼저 codex를 연결해주세요",
    "connect.body.connected": "Codex 연결 상태가 정상이라서, 이제 날짜를 고르면 바로 생성할 수 있어요.",
    "connect.body.default": "먼저 Codex 로그인 상태를 확인해야 해요.",
    "footer.ready": "날짜를 고르고 기록을 생성하면 앱 안에서 바로 일기와 보고서를 볼 수 있어요.",
    "footer.connectFirst": "먼저 Codex를 연결해 주세요.",
    "footer.generating": "Chronicle 요약을 읽고 선택한 날짜의 기록을 {{language}}로 만드는 중이에요...",
    "footer.generateFailed": "생성에 실패했어요.",
    "footer.connected": "날짜를 고르고 기록을 생성하면 앱 안에서 바로 일기와 보고서를 볼 수 있어요.",
    "footer.rechecked": "Codex 연결 상태를 다시 확인했어요.",
    "footer.connectFailed": "Codex 연결에 실패했어요.",
    "footer.noSavedForDate":
      "{{date}} 저장된 일기가 아직 없어요. 새로 생성하면 이 날짜 기록으로 덮어써집니다.",
    "footer.noSavedForDateCalendar":
      "{{date}} 저장된 일기가 아직 없어요. 생성하면 {{language}} 결과로 저장돼요.",
    "footer.openDiaryFailed": "{{date}} 일기를 열 수 없어요.",
    "footer.openedDiary": "{{date}} 일기를 열었어요.",
    "footer.openWeekFailed": "주간 보기를 열 수 없어요.",
    "footer.openedWeek": "{{label}} 주간 보기를 열었어요.",
    "footer.calendarHint": "캘린더 탭에서 날짜를 골라 기록을 이어서 볼 수 있어요.",
    "footer.generated": "{{date}} 일기를 {{language}}로 바로 열었어요.{{saved}}",
    "toast.codexReady": "Codex 준비 완료",
    "toast.sourceChanged": "입력 폴더를 바꿨어요",
    "toast.outputChanged": "출력 폴더를 바꿨어요",
    "toast.nothingToCopy": "복사할 내용이 없어요",
    "toast.copied": "복사했어요",
    "toast.copyFailed": "복사에 실패했어요",
    "toast.noSavedFile": "저장된 파일이 없어요",
    "toast.todayAdjusted": "오늘 기준 날짜로 맞췄어요",
    "toast.languageChanged": "언어를 {{language}}로 바꿨어요",
    "warning.webview": "WebView 브리지가 준비되지 않았어요.",
    "warning.timeout": "응답이 {{seconds}}초 안에 오지 않아요. Chronicle 폴더가 올바른지 확인해 주세요.",
    "mood.sparkle": "반짝",
    "mood.happy": "좋음",
    "mood.soft": "잔잔",
    "mood.tired": "지침",
    "mood.blue": "울적",
  },
  ja: {
    "brand.sub": "Chronicle の要約を日記に",
    "nav.diary": "日記",
    "nav.calendar": "カレンダー",
    "nav.archive": "保管庫",
    "side.recent": "最近の日付",
    "side.weekly": "週ごとの記録",
    "settings.title": "設定",
    "action.today": "今日へ",
    "view.diary": "日記",
    "view.report": "レポート",
    "menu.viewWeek": "この週を見る",
    "menu.copy": "現在の表示をコピー",
    "menu.external": "外部アプリで開く",
    "settings.languageLabel": "言語",
    "settings.boundaryLabel": "一日の区切り",
    "settings.modeLabel": "生成モード",
    "settings.modeFinalize": "最終日記",
    "settings.modeDraft": "下書きを更新",
    "settings.pathsSection": "パス",
    "settings.sourceLabel": "入力フォルダー",
    "settings.outputLabel": "出力フォルダー",
    "action.change": "変更",
    "diary.title": "今日の日記",
    "mood.label": "今日の気分",
    "summary.label": "今日の一行まとめ",
    "memo.save": "保存",
    "report.today": "今日やったこと",
    "report.highlights": "ハイライト",
    "report.blockers": "詰まった点",
    "report.tomorrow": "明日やること",
    "report.reflection": "短い振り返り",
    "timeline.title": "時系列の流れ",
    "calendar.weekSection": "週のまとめ",
    "archive.eyebrow": "保管庫",
    "archive.title": "日別記録と週ごとの束を一か所で",
    "side.emptyDaily": "保存された日記はまだありません",
    "side.emptyWeekly": "週の束はまだありません",
  },
  zh: {
    "brand.sub": "把 Chronicle 摘要变成日记",
    "nav.diary": "日记",
    "nav.calendar": "日历",
    "nav.archive": "归档",
    "side.recent": "最近日期",
    "side.weekly": "每周汇总",
    "settings.title": "设置",
    "action.today": "今天",
    "view.diary": "日记",
    "view.report": "报告",
    "menu.viewWeek": "查看本周",
    "menu.copy": "复制当前内容",
    "menu.external": "在外部应用中打开",
    "settings.languageLabel": "语言",
    "settings.boundaryLabel": "日期边界",
    "settings.modeLabel": "生成模式",
    "settings.modeFinalize": "最终日记",
    "settings.modeDraft": "更新草稿",
    "settings.pathsSection": "路径",
    "settings.sourceLabel": "输入文件夹",
    "settings.outputLabel": "输出文件夹",
    "action.change": "更改",
    "diary.title": "今日日记",
    "mood.label": "今天的心情",
    "summary.label": "今日一句总结",
    "memo.save": "保存",
    "report.today": "今天做了什么",
    "report.highlights": "重点",
    "report.blockers": "阻碍",
    "report.tomorrow": "明天要做的事",
    "report.reflection": "简短回顾",
    "timeline.title": "时间线",
    "calendar.weekSection": "每周汇总",
    "archive.eyebrow": "归档",
    "archive.title": "在一个地方查看每日记录和每周合集",
    "side.emptyDaily": "还没有已保存的日记",
    "side.emptyWeekly": "还没有每周合集",
  },
  fr: {
    "brand.sub": "Transformer les resumes Chronicle en journal",
    "nav.diary": "Journal",
    "nav.calendar": "Calendrier",
    "nav.archive": "Archive",
    "side.recent": "Dates recentes",
    "side.weekly": "Semaines",
    "settings.title": "Parametres",
    "action.today": "Aujourd'hui",
    "view.diary": "Journal",
    "view.report": "Rapport",
    "menu.viewWeek": "Voir cette semaine",
    "menu.copy": "Copier la vue actuelle",
    "menu.external": "Ouvrir dans une app externe",
    "settings.languageLabel": "Langue",
    "settings.boundaryLabel": "Limite du jour",
    "settings.modeLabel": "Mode de generation",
    "settings.modeFinalize": "Journal final",
    "settings.modeDraft": "Mettre a jour le brouillon",
    "settings.pathsSection": "Chemins",
    "settings.sourceLabel": "Dossier source",
    "settings.outputLabel": "Dossier de sortie",
    "action.change": "Modifier",
    "diary.title": "Journal du jour",
    "mood.label": "Humeur du jour",
    "summary.label": "Resume en une ligne",
    "memo.save": "Enregistrer",
    "report.today": "Ce que j'ai fait aujourd'hui",
    "report.highlights": "Points forts",
    "report.blockers": "Blocages",
    "report.tomorrow": "Demain",
    "report.reflection": "Courte retrospective",
    "timeline.title": "Chronologie",
    "calendar.weekSection": "Collections hebdomadaires",
    "archive.eyebrow": "Archive",
    "archive.title": "Parcourir les notes par jour et par semaine",
  },
  de: {
    "brand.sub": "Chronicle-Zusammenfassungen als Tagebuch",
    "nav.diary": "Tagebuch",
    "nav.calendar": "Kalender",
    "nav.archive": "Archiv",
    "side.recent": "Letzte Daten",
    "side.weekly": "Wochen",
    "settings.title": "Einstellungen",
    "action.today": "Heute",
    "view.diary": "Tagebuch",
    "view.report": "Bericht",
    "menu.viewWeek": "Diese Woche ansehen",
    "menu.copy": "Aktuelle Ansicht kopieren",
    "menu.external": "In externer App offnen",
    "settings.languageLabel": "Sprache",
    "settings.boundaryLabel": "Tagesgrenze",
    "settings.modeLabel": "Erzeugungsmodus",
    "settings.modeFinalize": "Finales Tagebuch",
    "settings.modeDraft": "Entwurf aktualisieren",
    "settings.pathsSection": "Pfade",
    "settings.sourceLabel": "Quellordner",
    "settings.outputLabel": "Ausgabeordner",
    "action.change": "Andern",
    "diary.title": "Heutiges Tagebuch",
    "mood.label": "Heutige Stimmung",
    "summary.label": "Ein-Satz-Zusammenfassung",
    "memo.save": "Speichern",
    "report.today": "Was ich heute gemacht habe",
    "report.highlights": "Highlights",
    "report.blockers": "Blocker",
    "report.tomorrow": "Morgen",
    "report.reflection": "Kurze Reflexion",
    "timeline.title": "Zeitlicher Verlauf",
    "calendar.weekSection": "Wochensammlungen",
    "archive.eyebrow": "Archiv",
    "archive.title": "Tagesnotizen und Wochenbundel an einem Ort",
  },
  es: {
    "brand.sub": "Convierte los resumenes de Chronicle en diario",
    "nav.diary": "Diario",
    "nav.calendar": "Calendario",
    "nav.archive": "Archivo",
    "side.recent": "Fechas recientes",
    "side.weekly": "Semanas",
    "settings.title": "Configuracion",
    "action.today": "Hoy",
    "view.diary": "Diario",
    "view.report": "Informe",
    "menu.viewWeek": "Ver esta semana",
    "menu.copy": "Copiar vista actual",
    "menu.external": "Abrir en app externa",
    "settings.languageLabel": "Idioma",
    "settings.boundaryLabel": "Limite del dia",
    "settings.modeLabel": "Modo de generacion",
    "settings.modeFinalize": "Diario final",
    "settings.modeDraft": "Actualizar borrador",
    "settings.pathsSection": "Rutas",
    "settings.sourceLabel": "Carpeta de origen",
    "settings.outputLabel": "Carpeta de salida",
    "action.change": "Cambiar",
    "diary.title": "Diario de hoy",
    "mood.label": "Estado de hoy",
    "summary.label": "Resumen en una linea",
    "memo.save": "Guardar",
    "report.today": "Lo que hice hoy",
    "report.highlights": "Aspectos clave",
    "report.blockers": "Bloqueos",
    "report.tomorrow": "Manana",
    "report.reflection": "Reflexion breve",
    "timeline.title": "Flujo cronologico",
    "calendar.weekSection": "Colecciones semanales",
    "archive.eyebrow": "Archivo",
    "archive.title": "Ver notas diarias y grupos semanales en un solo lugar",
  },
  vi: {
    "brand.sub": "Bien tong ket Chronicle thanh nhat ky",
    "nav.diary": "Nhat ky",
    "nav.calendar": "Lich",
    "nav.archive": "Luu tru",
    "side.recent": "Ngay gan day",
    "side.weekly": "Tong hop tuan",
    "settings.title": "Cai dat",
    "action.today": "Hom nay",
    "view.diary": "Nhat ky",
    "view.report": "Bao cao",
    "menu.viewWeek": "Xem tuan nay",
    "menu.copy": "Sao chep man hinh hien tai",
    "menu.external": "Mo bang ung dung ngoai",
    "settings.languageLabel": "Ngon ngu",
    "settings.boundaryLabel": "Moc ngay",
    "settings.modeLabel": "Che do tao",
    "settings.modeFinalize": "Nhat ky cuoi",
    "settings.modeDraft": "Cap nhat ban nhap",
    "settings.pathsSection": "Duong dan",
    "settings.sourceLabel": "Thu muc nguon",
    "settings.outputLabel": "Thu muc dau ra",
    "action.change": "Doi",
    "diary.title": "Nhat ky hom nay",
    "mood.label": "Tam trang hom nay",
    "summary.label": "Tom tat mot dong",
    "memo.save": "Luu",
    "report.today": "Hom nay da lam gi",
    "report.highlights": "Diem nhan",
    "report.blockers": "Diem nghen",
    "report.tomorrow": "Ngay mai",
    "report.reflection": "Nhin lai ngan",
    "timeline.title": "Dong thoi gian",
    "calendar.weekSection": "Tong hop theo tuan",
    "archive.eyebrow": "Luu tru",
    "archive.title": "Xem ghi chu theo ngay va tuan tai mot noi",
  },
  th: {
    "brand.sub": "เปลี่ยนสรุป Chronicle ให้เป็นไดอารี",
    "nav.diary": "ไดอารี",
    "nav.calendar": "ปฏิทิน",
    "nav.archive": "คลัง",
    "side.recent": "วันที่ล่าสุด",
    "side.weekly": "สรุปรายสัปดาห์",
    "settings.title": "ตั้งค่า",
    "action.today": "วันนี้",
    "view.diary": "ไดอารี",
    "view.report": "รายงาน",
    "menu.viewWeek": "ดูสัปดาห์นี้",
    "menu.copy": "คัดลอกมุมมองปัจจุบัน",
    "menu.external": "เปิดในแอปภายนอก",
    "settings.languageLabel": "ภาษา",
    "settings.boundaryLabel": "เส้นแบ่งวัน",
    "settings.modeLabel": "โหมดการสร้าง",
    "settings.modeFinalize": "ไดอารีฉบับสุดท้าย",
    "settings.modeDraft": "อัปเดตร่าง",
    "settings.pathsSection": "เส้นทาง",
    "settings.sourceLabel": "โฟลเดอร์ต้นทาง",
    "settings.outputLabel": "โฟลเดอร์ผลลัพธ์",
    "action.change": "เปลี่ยน",
    "diary.title": "ไดอารีของวันนี้",
    "mood.label": "อารมณ์วันนี้",
    "summary.label": "สรุปหนึ่งบรรทัด",
    "memo.save": "บันทึก",
    "report.today": "วันนี้ทำอะไรบ้าง",
    "report.highlights": "ไฮไลต์",
    "report.blockers": "จุดที่ติด",
    "report.tomorrow": "พรุ่งนี้",
    "report.reflection": "ทบทวนสั้นๆ",
    "timeline.title": "ลำดับเวลา",
    "calendar.weekSection": "ชุดรายสัปดาห์",
    "archive.eyebrow": "คลัง",
    "archive.title": "ดูบันทึกรายวันและรายสัปดาห์ในที่เดียว",
  },
  ru: {
    "brand.sub": "Превращайте сводки Chronicle в дневник",
    "nav.diary": "Дневник",
    "nav.calendar": "Календарь",
    "nav.archive": "Архив",
    "side.recent": "Последние даты",
    "side.weekly": "Недельные подборки",
    "settings.title": "Настройки",
    "action.today": "Сегодня",
    "view.diary": "Дневник",
    "view.report": "Отчет",
    "menu.viewWeek": "Открыть эту неделю",
    "menu.copy": "Копировать текущий вид",
    "menu.external": "Открыть во внешнем приложении",
    "settings.languageLabel": "Язык",
    "settings.boundaryLabel": "Граница дня",
    "settings.modeLabel": "Режим генерации",
    "settings.modeFinalize": "Итоговый дневник",
    "settings.modeDraft": "Обновить черновик",
    "settings.pathsSection": "Пути",
    "settings.sourceLabel": "Папка источника",
    "settings.outputLabel": "Папка вывода",
    "action.change": "Изменить",
    "diary.title": "Дневник за сегодня",
    "mood.label": "Настроение сегодня",
    "summary.label": "Краткое резюме",
    "memo.save": "Сохранить",
    "report.today": "Что я сделал сегодня",
    "report.highlights": "Главное",
    "report.blockers": "Блокеры",
    "report.tomorrow": "Завтра",
    "report.reflection": "Короткая рефлексия",
    "timeline.title": "Хронология",
    "calendar.weekSection": "Недельные подборки",
    "archive.eyebrow": "Архив",
    "archive.title": "Просматривайте дневные записи и недельные подборки в одном месте",
  },
  hi: {
    "brand.sub": "Chronicle सारांश को डायरी में बदलें",
    "nav.diary": "डायरी",
    "nav.calendar": "कैलेंडर",
    "nav.archive": "संग्रह",
    "side.recent": "हाल की तिथियां",
    "side.weekly": "साप्ताहिक संग्रह",
    "settings.title": "सेटिंग्स",
    "action.today": "आज",
    "view.diary": "डायरी",
    "view.report": "रिपोर्ट",
    "menu.viewWeek": "इस सप्ताह को देखें",
    "menu.copy": "मौजूदा दृश्य कॉपी करें",
    "menu.external": "बाहरी ऐप में खोलें",
    "settings.languageLabel": "भाषा",
    "settings.boundaryLabel": "दिन की सीमा",
    "settings.modeLabel": "जनरेशन मोड",
    "settings.modeFinalize": "अंतिम डायरी",
    "settings.modeDraft": "ड्राफ्ट अपडेट करें",
    "settings.pathsSection": "पथ",
    "settings.sourceLabel": "स्रोत फोल्डर",
    "settings.outputLabel": "आउटपुट फोल्डर",
    "action.change": "बदलें",
    "diary.title": "आज की डायरी",
    "mood.label": "आज का मूड",
    "summary.label": "एक पंक्ति सार",
    "memo.save": "सहेजें",
    "report.today": "आज मैंने क्या किया",
    "report.highlights": "मुख्य बातें",
    "report.blockers": "अटके हुए बिंदु",
    "report.tomorrow": "कल",
    "report.reflection": "छोटी समीक्षा",
    "timeline.title": "समय प्रवाह",
    "calendar.weekSection": "साप्ताहिक संग्रह",
    "archive.eyebrow": "संग्रह",
    "archive.title": "दैनिक नोट्स और साप्ताहिक समूह एक ही जगह देखें",
  },
};
